#include "configurations.h"
#include <stdexcept>
#include <sstream>

std::vector<occ_t> get_configuration(int Z) {
  std::vector<occ_t> ret;
  switch(Z) {
  case(1):
    ret.push_back(occ_t(0,1));
    break;
  case(2):
    ret.push_back(occ_t(0,2));
    break;

    // [He] core
  case(3):
    ret=get_configuration(2);
    ret.push_back(occ_t(0,1));
    break;
  case(4):
    ret=get_configuration(2);
    ret.push_back(occ_t(0,2));
    break;
  case(5):
    ret=get_configuration(2);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(1,1));
    break;
  case(6):
    ret=get_configuration(2);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(1,2));
    break;
  case(7):
    ret=get_configuration(2);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(1,3));
    break;
  case(8):
    ret=get_configuration(2);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(1,4));
    break;
  case(9):
    ret=get_configuration(2);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(1,5));
    break;
  case(10):
    ret=get_configuration(2);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(1,6));
    break;

    // [Ne] core
  case(11):
    ret=get_configuration(10);
    ret.push_back(occ_t(0,1));
    break;
  case(12):
    ret=get_configuration(10);
    ret.push_back(occ_t(0,2));
    break;
  case(13):
    ret=get_configuration(10);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(1,1));
    break;
  case(14):
    ret=get_configuration(10);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(1,2));
    break;
  case(15):
    ret=get_configuration(10);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(1,3));
    break;
  case(16):
    ret=get_configuration(10);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(1,4));
    break;
  case(17):
    ret=get_configuration(10);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(1,5));
    break;
  case(18):
    ret=get_configuration(10);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(1,6));
    break;

    // [Ar] core
  case(19):
    ret=get_configuration(18);
    ret.push_back(occ_t(0,1));
    break;
  case(20):
    ret=get_configuration(18);
    ret.push_back(occ_t(0,2));
    break;
  case(21):
    ret=get_configuration(18);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(2,1));
    break;
  case(22):
    ret=get_configuration(18);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(2,2));
    break;
  case(23):
    ret=get_configuration(18);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(2,3));
    break;
  case(24):
    ret=get_configuration(18);
    ret.push_back(occ_t(0,1));
    ret.push_back(occ_t(2,5));
    break;
  case(25):
    ret=get_configuration(18);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(2,5));
    break;
  case(26):
    ret=get_configuration(18);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(2,6));
    break;
  case(27):
    ret=get_configuration(18);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(2,7));
    break;
  case(28):
    ret=get_configuration(18);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(2,8));
    break;
  case(29):
    ret=get_configuration(18);
    ret.push_back(occ_t(0,1));
    ret.push_back(occ_t(2,10));
    break;
  case(30):
    ret=get_configuration(18);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(2,10));
    break;
  case(31):
    ret=get_configuration(18);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(2,10));
    ret.push_back(occ_t(1,1));
    break;
  case(32):
    ret=get_configuration(18);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(2,10));
    ret.push_back(occ_t(1,2));
    break;
  case(33):
    ret=get_configuration(18);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(2,10));
    ret.push_back(occ_t(1,3));
    break;
  case(34):
    ret=get_configuration(18);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(2,10));
    ret.push_back(occ_t(1,4));
    break;
  case(35):
    ret=get_configuration(18);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(2,10));
    ret.push_back(occ_t(1,5));
    break;
  case(36):
    ret=get_configuration(18);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(2,10));
    ret.push_back(occ_t(1,6));
    break;

    // [Kr] core
  case(37):
    ret=get_configuration(36);
    ret.push_back(occ_t(0,1));
    break;
  case(38):
    ret=get_configuration(36);
    ret.push_back(occ_t(0,2));
    break;
  case(39):
    ret=get_configuration(36);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(2,1));
    break;
  case(40):
    ret=get_configuration(36);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(2,2));
    break;
  case(41):
    ret=get_configuration(36);
    ret.push_back(occ_t(0,1));
    ret.push_back(occ_t(2,4));
    break;
  case(42):
    ret=get_configuration(36);
    ret.push_back(occ_t(0,1));
    ret.push_back(occ_t(2,5));
    break;
  case(43):
    ret=get_configuration(36);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(2,5));
    break;
  case(44):
    ret=get_configuration(36);
    ret.push_back(occ_t(0,1));
    ret.push_back(occ_t(2,7));
    break;
  case(45):
    ret=get_configuration(36);
    ret.push_back(occ_t(0,1));
    ret.push_back(occ_t(2,8));
    break;
  case(46):
    ret=get_configuration(36);
    ret.push_back(occ_t(2,10));
    break;
  case(47):
    ret=get_configuration(36);
    ret.push_back(occ_t(0,1));
    ret.push_back(occ_t(2,10));
    break;
  case(48):
    ret=get_configuration(36);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(2,10));
    break;
  case(49):
    ret=get_configuration(36);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(2,10));
    ret.push_back(occ_t(1,1));
    break;
  case(50):
    ret=get_configuration(36);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(2,10));
    ret.push_back(occ_t(1,2));
    break;
  case(51):
    ret=get_configuration(36);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(2,10));
    ret.push_back(occ_t(1,3));
    break;
  case(52):
    ret=get_configuration(36);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(2,10));
    ret.push_back(occ_t(1,4));
    break;
  case(53):
    ret=get_configuration(36);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(2,10));
    ret.push_back(occ_t(1,5));
    break;
  case(54):
    ret=get_configuration(36);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(2,10));
    ret.push_back(occ_t(1,6));
    break;

    // [Xe] core
  case(55):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,1));
    break;
  case(56):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,2));
    break;
  case(57):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(2,1));
    break;
  case(58):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(2,1));
    ret.push_back(occ_t(3,1));
    break;
  case(59):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(3,3));
    break;
  case(60):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(3,4));
    break;
  case(61):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(3,5));
    break;
  case(62):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(3,6));
    break;
  case(63):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(3,7));
    break;
  case(64):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(2,1));
    ret.push_back(occ_t(3,7));
    break;
  case(65):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(3,9));
    break;
  case(66):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(3,10));
    break;
  case(67):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(3,11));
    break;
  case(68):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(3,12));
    break;
  case(69):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(3,13));
    break;
  case(70):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(3,14));
    break;
  case(71):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(2,1));
    ret.push_back(occ_t(3,14));
    break;
  case(72):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(2,2));
    ret.push_back(occ_t(3,14));
    break;
  case(73):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(2,3));
    ret.push_back(occ_t(3,14));
    break;
  case(74):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(2,4));
    ret.push_back(occ_t(3,14));
    break;
  case(75):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(2,5));
    ret.push_back(occ_t(3,14));
    break;
  case(76):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(2,6));
    ret.push_back(occ_t(3,14));
    break;
  case(77):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(2,7));
    ret.push_back(occ_t(3,14));
    break;
  case(78):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,1));
    ret.push_back(occ_t(2,9));
    ret.push_back(occ_t(3,14));
    break;
  case(79):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,1));
    ret.push_back(occ_t(2,10));
    ret.push_back(occ_t(3,14));
    break;
  case(80):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(2,10));
    ret.push_back(occ_t(3,14));
    break;
  case(81):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(1,1));
    ret.push_back(occ_t(2,10));
    ret.push_back(occ_t(3,14));
    break;
  case(82):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(1,2));
    ret.push_back(occ_t(2,10));
    ret.push_back(occ_t(3,14));
    break;
  case(83):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(1,3));
    ret.push_back(occ_t(2,10));
    ret.push_back(occ_t(3,14));
    break;
  case(84):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(1,4));
    ret.push_back(occ_t(2,10));
    ret.push_back(occ_t(3,14));
    break;
  case(85):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(1,5));
    ret.push_back(occ_t(2,10));
    ret.push_back(occ_t(3,14));
    break;
  case(86):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(1,6));
    ret.push_back(occ_t(2,10));
    ret.push_back(occ_t(3,14));
    break;

    // [Rn] core
  case(87):
    ret=get_configuration(86);
    ret.push_back(occ_t(0,1));
    break;
  case(88):
    ret=get_configuration(86);
    ret.push_back(occ_t(0,2));
    break;
  case(89):
    ret=get_configuration(86);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(2,1));
    break;
  case(90):
    ret=get_configuration(86);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(2,2));
    break;
  case(91):
    ret=get_configuration(86);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(2,1));
    ret.push_back(occ_t(3,2));
    break;
  case(92):
    ret=get_configuration(86);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(2,1));
    ret.push_back(occ_t(3,3));
    break;

  default:
    std::ostringstream oss;
    oss << "Unsupported element Z = " << Z << ".\n";
    throw std::logic_error(oss.str());
  }

  return ret;
}

std::vector<occ_t> get_cationic_configuration(int Z) {
  std::vector<occ_t> ret;
  switch(Z) {
  case(1):
    break;
  case(21):
    ret=get_configuration(18);
    ret.push_back(occ_t(0,1));
    ret.push_back(occ_t(2,1));
    break;
  case(22):
    ret=get_configuration(18);
    ret.push_back(occ_t(0,1));
    ret.push_back(occ_t(2,2));
    break;
  case(23):
    ret=get_configuration(18);
    ret.push_back(occ_t(2,4));
    break;
  case(24):
    ret=get_configuration(18);
    ret.push_back(occ_t(2,5));
    break;
  case(26):
    ret=get_configuration(18);
    ret.push_back(occ_t(0,1));
    ret.push_back(occ_t(2,6));
    break;
  case(27):
    ret=get_configuration(18);
    ret.push_back(occ_t(2,8));
    break;
  case(28):
    ret=get_configuration(18);
    ret.push_back(occ_t(2,9));
    break;
  case(29):
    ret=get_configuration(18);
    ret.push_back(occ_t(2,10));
    break;

  case(41):
    ret=get_configuration(36);
    ret.push_back(occ_t(2,4));
    break;
  case(42):
    ret=get_configuration(36);
    ret.push_back(occ_t(2,5));
    break;
  case(44):
    ret=get_configuration(36);
    ret.push_back(occ_t(2,7));
    break;
  case(45):
    ret=get_configuration(36);
    ret.push_back(occ_t(2,8));
    break;
  case(46):
    ret=get_configuration(36);
    ret.push_back(occ_t(2,9));
    break;


  case(57):
    ret=get_configuration(54);
    ret.push_back(occ_t(2,2));
    break;
  case(58):
    ret=get_configuration(54);
    ret.push_back(occ_t(2,2));
    ret.push_back(occ_t(3,1));
    break;
  case(59):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,1));
    ret.push_back(occ_t(3,3));
    break;
  case(60):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,1));
    ret.push_back(occ_t(3,4));
    break;
  case(61):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,1));
    ret.push_back(occ_t(3,5));
    break;
  case(62):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,1));
    ret.push_back(occ_t(3,6));
    break;
  case(63):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,1));
    ret.push_back(occ_t(3,7));
    break;
  case(64):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,1));
    ret.push_back(occ_t(2,1));
    ret.push_back(occ_t(3,7));
    break;
  case(65):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,1));
    ret.push_back(occ_t(3,9));
    break;
  case(66):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,1));
    ret.push_back(occ_t(3,10));
    break;
  case(67):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,1));
    ret.push_back(occ_t(3,11));
    break;
  case(68):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,1));
    ret.push_back(occ_t(3,12));
    break;
  case(69):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,1));
    ret.push_back(occ_t(3,13));
    break;
  case(70):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,1));
    ret.push_back(occ_t(3,14));
    break;

  case(73):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,1));
    ret.push_back(occ_t(2,3));
    ret.push_back(occ_t(3,14));
    break;
  case(74):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,1));
    ret.push_back(occ_t(2,4));
    ret.push_back(occ_t(3,14));
    break;
  case(75):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,1));
    ret.push_back(occ_t(2,5));
    ret.push_back(occ_t(3,14));
    break;
  case(76):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,1));
    ret.push_back(occ_t(2,6));
    ret.push_back(occ_t(3,14));
    break;
  case(77):
    ret=get_configuration(54);
    ret.push_back(occ_t(0,1));
    ret.push_back(occ_t(2,7));
    ret.push_back(occ_t(3,14));
    break;
  case(78):
    ret=get_configuration(54);
    ret.push_back(occ_t(2,9));
    ret.push_back(occ_t(3,14));
    break;
  case(79):
    ret=get_configuration(54);
    ret.push_back(occ_t(2,10));
    ret.push_back(occ_t(3,14));
    break;

  case(90):
    ret=get_configuration(86);
    ret.push_back(occ_t(0,1));
    ret.push_back(occ_t(2,2));
    break;
  case(91):
    ret=get_configuration(86);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(3,2));
    break;
  case(92):
    ret=get_configuration(86);
    ret.push_back(occ_t(0,2));
    ret.push_back(occ_t(3,3));
    break;

  default:
    ret=get_configuration(Z-1);
  }

  return ret;
}
