#
#                This source code is part of
#
#                          HelFEM
#                             -
# Finite element methods for electronic structure calculations on small systems
#
# Written by Susi Lehtola, 2018-
# Copyright (c) 2018- Susi Lehtola
#
# SPDX-License-Identifier: BSD-3-Clause
# See the LICENSE file at the root of this source distribution
# for the full license text.
#
# Code generator for arbitrary-order derivatives of LIP (Lagrange
# interpolating polynomial) basis functions.
#
# v2 refactor: emits a templated header for libhelfem. The generated
# function is a free template (lives in
# helfem::polynomial_basis::detail::eval_lip_prim_dnf) so
# both the LIPBasisT<T> primitive basis and any future caller can use it at any
# scalar type T.
#
# Run with:
#     python3 generate_lip_code.py > ../include/LIPBasis_eval.h
#
# The output is checked in; SymPy is NOT required (this script uses
# only plain Python).

kahan = False
maxorder = 21

print('''/*
 * This file is autogenerated by libhelfem/src/generate_lip_code.py.
 *
 *                This source code is part of
 *                          HelFEM
 *
 * Written by Susi Lehtola, 2018-
 * Copyright (c) 2018- Susi Lehtola
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
#ifndef LIB1DFEM_LIPBASIS_EVAL_H
#define LIB1DFEM_LIPBASIS_EVAL_H

#include <types.h>
#include <sstream>
#include <stdexcept>

namespace helfem {
namespace polynomial_basis {
namespace detail {

/// Evaluate the n-th derivative of every LIP polynomial on the reference
/// element [-1, 1] at the given points x, given the control-node vector
/// x0. Fills dnf (size x.size() x x0.size()) with d^n L_i(x_j)/dx^n in
/// column-major (point, polynomial) layout. element_length is unused
/// at this layer (the chain-rule scaling lives in PolynomialBasis::eval_dnf).
template <typename T>
void eval_lip_prim_dnf(const Vec<T> & x, const Vec<T> & x0,
                       Mat<T> & dnf, int n) {
  switch (n) {''')

for order in range(0, maxorder):
    fname = 'dnf'
    print('case ({}): {{'.format(order))
    print('  {}.setZero((Eigen::Index) x.size(), (Eigen::Index) x0.size());'.format(fname))
    print('  for (size_t ix = 0; ix < (size_t) x.size(); ix++) {')
    print('    for (size_t fi = 0; fi < (size_t) x0.size(); fi++) {')
    if order > 0:
        if kahan:
            print('      T s = T(0), s2 = T(0), t;')
        else:
            print('      T el = T(0);')

    # Derivative loops
    factor = 1
    for ider in range(1, order + 1):
        print('      for (size_t d{0} = 0; d{0} < {1}; d{0}++) {{'.format(
            ider, '(size_t) x0.size()' if ider == 1 else 'd{}'.format(ider - 1)))
        for term in ['fi']:
            print('        if (d{0} == {1}) continue;'.format(ider, term))
        factor *= ider

    # Now do the product
    print('      T {}val = T(1);'.format(fname))
    print('      for (size_t ip = 0; ip < (size_t) x0.size(); ip++) {')
    check_terms = ['d{}'.format(o) for o in range(1, order + 1)]
    check_terms.append('fi')
    for term in check_terms:
        print('        if (ip == {}) continue;'.format(term))
    print('        {}val *= (x(ix) - x0(ip)) / (x0(fi) - x0(ip));'.format(fname))
    print('      }')

    div_terms = ['(x0(fi) - x0(d{}))'.format(o) for o in range(1, order + 1)]
    if div_terms:
        print('      {}val /= '.format(fname) + ' * '.join(div_terms) + ';')

    if order > 0:
        if kahan:
            print('      s2 = s2 + {0}val;'.format(fname))
            print('      t = s + s2;')
            print('      s2 = (s - t) + s2;')
            print('      s = t;')
            for _ in range(order):
                print('      }')
            print('      {0}(ix, fi) = {1}s;'.format(
                fname, 'T({})*'.format(factor) if factor > 1 else ''))
        else:
            print('      el += {0}val;'.format(fname))
            for _ in range(order):
                print('      }')
            print('      {0}(ix, fi) = {1}el;'.format(
                fname, 'T({})*'.format(factor) if factor > 1 else ''))
    else:
        print('      {0}(ix, fi) = {1}{0}val;'.format(
            fname, 'T({})*'.format(factor) if factor > 1 else ''))

    print('    }')
    print('  }')
    print('} break;')

print('default: {')
print('  std::ostringstream oss;')
print('  oss << n << "th derivatives not implemented!\\n";')
print('  throw std::logic_error(oss.str());')
print('}')
print('  }')  # close switch
print('}')    # close eval_lip_prim_dnf

print('''
} // namespace detail
} // namespace polynomial_basis
} // namespace helfem

#endif''')
