#
#                This source code is part of
#
#                          HelFEM
#                             -
# Finite element methods for electronic structure calculations on small systems
#
# Written by Susi Lehtola, 2018-
# Copyright (c) 2018- Susi Lehtola
#
# SPDX-License-Identifier: BSD-3-Clause
# See the LICENSE file at the root of this source distribution
# for the full license text.
#
# Code generator for arbitrary-order derivatives of HIP (Hermite
# interpolating polynomial) basis functions.
#
# v2 refactor: emits a templated header for lib1dfem. The generated
# function is a free template
#     helfem::lib1dfem::polynomial_basis::detail::eval_hip_prim_dnf<T>
# so it can be instantiated at any scalar T.
#
# Run with:
#     python3 generate_hip_code.py > ../../lib1dfem/include/lib1dfem/HIPBasis_eval.h
#
# Plain Python (no SymPy).

import copy

maxorder = 21

print('''/*
 * This file is autogenerated by libhelfem/src/generate_hip_code.py.
 *
 *                This source code is part of
 *                          HelFEM
 *
 * Written by Susi Lehtola, 2018-
 * Copyright (c) 2018- Susi Lehtola
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
#ifndef LIB1DFEM_HIPBASIS_EVAL_H
#define LIB1DFEM_HIPBASIS_EVAL_H

#include <armadillo>
#include <lib1dfem/LIPBasis_eval.h>
#include <sstream>
#include <stdexcept>

namespace helfem {
namespace lib1dfem {
namespace polynomial_basis {
namespace detail {

/// Evaluate the n-th derivative of every HIP basis function on the
/// reference element [-1, 1] at the given points x, given control nodes
/// x0 and the precomputed LIP-derivative-at-nodes vector lipxi. Fills
/// dnf (size x.n_elem x 2*x0.n_elem) with paired function-and-derivative
/// shape functions:
///   - column 2*fi   : the value-interpolating Hermite function for node fi
///   - column 2*fi+1 : the derivative-interpolating Hermite function for node fi
/// scaled by element_length on the derivative slot.
template <typename T>
void eval_hip_prim_dnf(const arma::Col<T> & x, const arma::Col<T> & x0,
                       const arma::Col<T> & lipxi,
                       arma::Mat<T> & dnf, int n, T element_length) {
  switch (n) {''')


def get_fname(order):
    if order == 0:
        return 'f'
    if order == 1:
        return 'df'
    return 'd{}f'.format(order)


# Recurrence: derivative of L_i(x)^2 via product rule.
# Represent d^k[L^2] as a sum_{(a,b)} c_{a,b} * L^(a) * L^(b)
Lider = [{(0, 0): 1}]
for _ in range(maxorder):
    prev = copy.deepcopy(Lider[-1])
    cur = {}
    for fun, coef in prev.items():
        for term in [(fun[0] + 1, fun[1]), (fun[0], fun[1] + 1)]:
            oterm = (max(term), min(term))
            cur[oterm] = cur.get(oterm, 0) + coef
    Lider.append(cur)


def emit_term(label, Li):
    parts = []
    for term, coef in Li.items():
        prefix = ''
        if coef != 1:
            prefix = 'T({}) * '.format(coef)
        parts.append('{}{}lip(ix, fi) * {}lip(ix, fi)'.format(
            prefix, get_fname(term[0]), get_fname(term[1])))
    return 'T {} = '.format(label) + ' + '.join(parts) + ';'


for order in range(0, maxorder):
    fname = 'dnf'
    print('case ({}): {{'.format(order))
    print('  {}.zeros(x.n_elem, 2 * x0.n_elem);'.format(fname))
    for olip in range(order + 1):
        print('  arma::Mat<T> {0}lip;'.format(get_fname(olip)))
        print('  eval_lip_prim_dnf<T>(x, x0, {0}lip, {1});'.format(
            get_fname(olip), olip))
    print('  for (size_t ix = 0; ix < x.n_elem; ix++) {')
    print('    for (size_t fi = 0; fi < x0.n_elem; fi++) {')
    print('      // First shape function:  [1 - 2(x-xi)*lipxi(fi)] * L_i(x)^2  =  f1 * f2')
    print('      // Second shape function: (x-xi) * L_i(x)^2                    =  f3 * f2')
    print('      T f1 = T(1) - T(2) * (x(ix) - x0(fi)) * lipxi(fi);')
    if order > 0:
        print('      T df1 = -T(2) * lipxi(fi);')
    print('      T f3 = x(ix) - x0(fi);')
    if order > 0:
        print('      T df3 = T(1);')

    if order > 0:
        print('      ' + emit_term('{}2'.format(get_fname(order - 1)), Lider[order - 1]))
    print('      ' + emit_term('{}2'.format(get_fname(order)), Lider[order]))

    if order == 0:
        print('      {0}(ix, 2*fi)     = f1 * f2;'.format(fname))
        print('      {0}(ix, 2*fi + 1) = f3 * f2 * element_length;'.format(fname))
    else:
        print('      {0}(ix, 2*fi)     = T({1}) * {2}1 * {3}2 + {4}1 * {5}2;'.format(
            fname, order, get_fname(1), get_fname(order - 1),
            get_fname(0), get_fname(order)))
        print('      {0}(ix, 2*fi + 1) = (T({1}) * {2}3 * {3}2 + {4}3 * {5}2) * element_length;'.format(
            fname, order, get_fname(1), get_fname(order - 1),
            get_fname(0), get_fname(order)))

    print('    }')
    print('  }')
    print('} break;')

print('default: {')
print('  std::ostringstream oss;')
print('  oss << n << "th derivatives not implemented!\\n";')
print('  throw std::logic_error(oss.str());')
print('}')
print('  }')
print('}')

print('''
} // namespace detail
} // namespace polynomial_basis
} // namespace lib1dfem
} // namespace helfem

#endif''')
