#
#                This source code is part of
#
#                          HelFEM
#                             -
# Finite element methods for electronic structure calculations on small systems
#
# Written by Susi Lehtola, 2018-
# Copyright (c) 2018- Susi Lehtola
#
# SPDX-License-Identifier: BSD-3-Clause
# See the LICENSE file at the root of this source distribution
# for the full license text.
#
# Symbolic derivation + C++ emitter for the analytic HIP3 (third-order
# Hermite interpolating polynomial) shape functions. Same pattern as
# generate_hip2_code.py, one degree higher: each node x_i carries four
# shape functions h_{i,0}, h_{i,1}, h_{i,2}, h_{i,3} that interpolate
# value, first, second, and third r-derivative respectively:
#
#     h_{i,j}^(m)(x_n) = delta_{in} delta_{jm}   for j, m in {0,1,2,3}.
#
# With p(x) = L_i(x), the construction gives
#     h_{i,j}(x) = p(x)^4 * q_j(x - x_i)
# where q_j is a degree-3 polynomial in (x - x_i). Coefficients are
# computed by solving the interpolation linear system at x = x_i; the
# solution involves p'(x_i), p''(x_i), p'''(x_i) (precomputed at
# construction).
#
# This emitter prints orders 0..2 only (post-Taylor scope: RadialBasis
# does not need higher orders). Higher orders throw at runtime.
#
# Run with:
#   python3 generate_hip3_code.py > ../../lib1dfem/include/lib1dfem/HIP3Basis_eval.h

import re
import sympy as sp

# Use the C++ variable names directly in the SymPy symbols so emitted
# ccode is drop-in.
xv      = sp.Symbol('xv',      real=True)  # integration point
xi      = sp.Symbol('xi',      real=True)  # node position x_i
Lx      = sp.Symbol('Lx',      real=True)  # L_i(xv)
dLx     = sp.Symbol('dLx',     real=True)  # L_i'(xv)
ddLx    = sp.Symbol('ddLx',    real=True)  # L_i''(xv)
dLxi_v  = sp.Symbol('dLxi_v',  real=True)  # L_i'(x_i)
ddLxi_v = sp.Symbol('ddLxi_v', real=True)  # L_i''(x_i)
dddLxi_v = sp.Symbol('dddLxi_v', real=True)  # L_i'''(x_i)

# (p^4) and its first three x-derivatives, expressed in (Lx, dLx, ddLx).
# (p^4)''' has a p''' term that depends on L_i'''(xv) -- we don't need it
# for orders 0..2, so the emit loop only goes up to (p^4)''.
p4    = Lx**4
p4_d  = 4*Lx**3 * dLx
p4_dd = 12*Lx**2*dLx**2 + 4*Lx**3*ddLx

# Coefficients of q_j(t) = a + b t + c t^2 + d t^3, found by enforcing
# h_{i,j}^(m)(x_i) = delta_{jm} for m, j in {0..3}.
p1 = dLxi_v
p2 = ddLxi_v
p3 = dddLxi_v

# Solve symbolically (cleanest, avoids hand-computed coefficients).
a, b, c, d = sp.symbols('a b c d', real=True)
t          = xv - xi
q_generic  = a + b*t + c*t**2 + d*t**3
qd_generic = sp.diff(q_generic, xv)
qdd_generic= sp.diff(q_generic, xv, 2)
qddd_generic = sp.diff(q_generic, xv, 3)

# h_{i,j}(x_i) etc. -- evaluate the Leibniz expansion at x = x_i with
# p(x_i)=1, p'(x_i)=p1, p''(x_i)=p2, p'''(x_i)=p3.
def h_at_xi(qval, qdval, qddval, qdddval, order):
    # (p^4) and its derivatives at x_i with p(x_i)=1.
    P0  = 1
    P1  = 4 * p1
    P2  = 12 * p1**2 + 4 * p2
    P3  = 24 * p1**3 + 36 * p1*p2 + 4 * p3
    if order == 0:
        return P0 * qval
    if order == 1:
        return P1 * qval + P0 * qdval
    if order == 2:
        return P2 * qval + 2*P1 * qdval + P0 * qddval
    if order == 3:
        return P3 * qval + 3*P2 * qdval + 3*P1 * qddval + P0 * qdddval
    raise ValueError

# Solve the 4 systems (one per shape j).
shape_coeffs = []
for j in range(4):
    eqs = []
    for m in range(4):
        target = 1 if m == j else 0
        eqs.append(
            sp.Eq(h_at_xi(q_generic.subs(xv, xi),
                          qd_generic.subs(xv, xi),
                          qdd_generic.subs(xv, xi),
                          qddd_generic.subs(xv, xi),
                          m), target))
    sol = sp.solve(eqs, [a, b, c, d])
    shape_coeffs.append(sol)

# Now build h_{i,j}(x) = p(x)^4 * q_j(x - x_i).
def hpoly(j):
    sol = shape_coeffs[j]
    q_j = q_generic.subs(sol)
    return sp.expand(Lx**4 * q_j)

# h and first two x-derivatives via Leibniz on p^4 * q, where:
#   (p^4)^(k) substituted from p4, p4_d, p4_dd
#   q^(k) computed by directly differentiating q_j(x-xi) wrt xv
def hpow_deriv(j, n):
    q_j   = q_generic.subs(shape_coeffs[j])
    q_d   = sp.diff(q_j, xv)
    q_dd  = sp.diff(q_j, xv, 2)
    if n == 0:
        return p4 * q_j
    if n == 1:
        return p4_d * q_j + p4 * q_d
    if n == 2:
        return p4_dd * q_j + 2*p4_d * q_d + p4 * q_dd
    raise ValueError(f"derivative order {n} not handled")


print('''/*
 * This file is autogenerated by libhelfem/src/generate_hip3_code.py.
 *
 *                This source code is part of
 *                          HelFEM
 *
 * Written by Susi Lehtola, 2018-
 * Copyright (c) 2018- Susi Lehtola
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
#ifndef LIB1DFEM_HIP3BASIS_EVAL_H
#define LIB1DFEM_HIP3BASIS_EVAL_H

#include <armadillo>
#include <lib1dfem/LIPBasis_eval.h>
#include <sstream>
#include <stdexcept>

namespace helfem {
namespace lib1dfem {
namespace polynomial_basis {
namespace detail {

/// Evaluate the n-th derivative w.r.t. x of every HIP3 shape function on
/// the reference element [-1, 1] at the given points x. Four shape
/// functions per node:
///   column 4*fi   = value interpolant h_{i,0}
///   column 4*fi+1 = first-derivative interpolant h_{i,1}
///   column 4*fi+2 = second-derivative interpolant h_{i,2}
///   column 4*fi+3 = third-derivative interpolant h_{i,3}
/// (Layout matches the GeneralHIPBasis(nder=3) ordering.)
///
/// x0      : node positions (sorted ascending, including endpoints).
/// lipxi   : L_i^(1)(x_i) for every node i  (precomputed at construction).
/// lipxi2  : L_i^(2)(x_i) for every node i  (ditto).
/// lipxi3  : L_i^(3)(x_i) for every node i  (ditto).
/// element_length : FE scaling_factor. The j-th derivative interpolant
///                  is scaled by element_length^j so its j-th r-derivative
///                  at the node equals 1 in physical units (matches
///                  PolynomialBasis::eval_dnf convention).
///
/// Implemented for n in {0, 1, 2}; higher orders throw -- they're not
/// needed once the Taylor pipeline in RadialBasis has been retired
/// (see PR #69).
template <typename T>
void eval_hip3_prim_dnf(const arma::Col<T> & x, const arma::Col<T> & x0,
                        const arma::Col<T> & lipxi, const arma::Col<T> & lipxi2,
                        const arma::Col<T> & lipxi3,
                        arma::Mat<T> & dnf, int n, T element_length) {
  switch (n) {''')


def emit_T_typed(expr):
    code = sp.ccode(sp.expand(expr))
    code = re.sub(r'(?<![\w.])([0-9]+)(?:\.0)?(?![\w.])', r'T(\1)', code)
    return code


for n in range(3):
    needed_lip_orders = list(range(n + 1))
    print(f'case ({n}): {{')
    print(f'  dnf.zeros(x.n_elem, 4 * x0.n_elem);')
    for k in needed_lip_orders:
        name = ['Lx_all', 'dLx_all', 'ddLx_all'][k]
        print(f'  arma::Mat<T> {name};')
        print(f'  eval_lip_prim_dnf<T>(x, x0, {name}, {k});')
    print(f'  for (size_t ix = 0; ix < x.n_elem; ix++) {{')
    print(f'    for (size_t fi = 0; fi < x0.n_elem; fi++) {{')
    print(f'      const T xv       = x(ix);')
    print(f'      const T xi       = x0(fi);')
    print(f'      const T Lx       = Lx_all(ix, fi);')
    if n >= 1:
        print(f'      const T dLx      = dLx_all(ix, fi);')
    if n >= 2:
        print(f'      const T ddLx     = ddLx_all(ix, fi);')
    print(f'      const T dLxi_v   = lipxi(fi);')
    print(f'      const T ddLxi_v  = lipxi2(fi);')
    print(f'      const T dddLxi_v = lipxi3(fi);')
    print(f'      // SymPy-derived closed forms for d^{n}/dx^{n} of each HIP3 shape:')
    for j in range(4):
        print(f'      dnf(ix, 4*fi + {j}) = {emit_T_typed(hpow_deriv(j, n))};')
    print(f'      dnf(ix, 4*fi + 1) *= element_length;')
    print(f'      dnf(ix, 4*fi + 2) *= element_length * element_length;')
    print(f'      dnf(ix, 4*fi + 3) *= element_length * element_length * element_length;')
    print(f'    }}')
    print(f'  }}')
    print(f'}} break;')


print('default: {')
print('  std::ostringstream oss;')
print('  oss << "HIP3Basis: derivative order " << n')
print('      << " not implemented (only 0, 1, 2 supported).\\n";')
print('  throw std::logic_error(oss.str());')
print('}')
print('  }')
print('}')

print('''
} // namespace detail
} // namespace polynomial_basis
} // namespace lib1dfem
} // namespace helfem

#endif''')
