#
#                This source code is part of
#
#                          HelFEM
#                             -
# Finite element methods for electronic structure calculations on small systems
#
# Written by Susi Lehtola, 2018-
# Copyright (c) 2018- Susi Lehtola
#
# SPDX-License-Identifier: BSD-3-Clause
# See the LICENSE file at the root of this source distribution
# for the full license text.
#
# Symbolic derivation + C++ emitter for the analytic HIP2 (second-order
# Hermite interpolating polynomial) shape functions.
#
# At each node x_i, three shape functions h_{i,0}, h_{i,1}, h_{i,2}
# interpolate value, first derivative, and second derivative:
#
#     h_{i,j}^(m)(x_n) = delta_{in} delta_{jm}   for j, m in {0, 1, 2}.
#
# Writing p(x) = L_i(x) (the Lagrange polynomial for node i on the full
# node set), the standard construction gives
#
#     h_{i,j}(x) = p(x)^3 * q_j(x - x_i)
#
# with degree-2 polynomials q_j(t) determined by the interpolation
# conditions at x = x_i:
#
#     q_0(t) = 1 - 3 p'(x_i) t + (6 p'(x_i)^2 - (3/2) p''(x_i)) t^2
#     q_1(t) = t - 3 p'(x_i) t^2
#     q_2(t) = t^2 / 2
#
# At any other node x_n != x_i, h_{i,j}(x_n) and its derivatives vanish
# automatically because p(x_n) = L_i(x_n) = 0 carries the cubic factor.
#
# Run with:
#   python3 generate_hip2_code.py > ../../lib1dfem/include/lib1dfem/HIP2Basis_eval.h

import sympy as sp

# Use the C++ variable names directly in the SymPy symbols so we don't
# need any post-processing rename pass.
xv      = sp.Symbol('xv',      real=True)  # integration point
xi      = sp.Symbol('xi',      real=True)  # node position x_i
Lx      = sp.Symbol('Lx',      real=True)  # L_i(xv)
dLx     = sp.Symbol('dLx',     real=True)  # L_i'(xv)
ddLx    = sp.Symbol('ddLx',    real=True)  # L_i''(xv)
dLxi_v  = sp.Symbol('dLxi_v',  real=True)  # L_i'(x_i), precomputed
ddLxi_v = sp.Symbol('ddLxi_v', real=True)  # L_i''(x_i), precomputed

# SymPy can't directly differentiate "an unknown function p with known
# derivatives at x". So we model p^3 and its derivatives explicitly via
# the chain rule:
#   d/dx [p^3]   = 3 p^2 p'
#   d^2/dx^2 [p^3] = 6 p (p')^2 + 3 p^2 p''
# in terms of (Lx, dLx, ddLx).
p3   = Lx**3
p3_d = 3*Lx**2 * dLx
p3_dd = 6*Lx*dLx**2 + 3*Lx**2*ddLx

t = xv - xi
q = [
    1 - 3*dLxi_v*t + (6*dLxi_v**2 - sp.Rational(3, 2)*ddLxi_v)*t**2,
    t - 3*dLxi_v*t**2,
    t**2 / 2,
]
# d q_j / dxv
qd = [sp.diff(q_j, xv) for q_j in q]
# d^2 q_j / dxv^2
qdd = [sp.diff(q_j, xv, 2) for q_j in q]

# h_{i,j}(x) and its first two x-derivatives via Leibniz:
#   h  = p^3 q
#   h' = (p^3)' q + p^3 q'
#   h''= (p^3)'' q + 2 (p^3)' q' + p^3 q''
def hpow_deriv(j, n):
    if n == 0:
        return p3 * q[j]
    if n == 1:
        return p3_d * q[j] + p3 * qd[j]
    if n == 2:
        return p3_dd * q[j] + 2*p3_d * qd[j] + p3 * qdd[j]
    raise ValueError(f"derivative order {n} not handled")

print('''/*
 * This file is autogenerated by libhelfem/src/generate_hip2_code.py.
 *
 *                This source code is part of
 *                          HelFEM
 *
 * Written by Susi Lehtola, 2018-
 * Copyright (c) 2018- Susi Lehtola
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
#ifndef LIB1DFEM_HIP2BASIS_EVAL_H
#define LIB1DFEM_HIP2BASIS_EVAL_H

#include <armadillo>
#include <lib1dfem/LIPBasis_eval.h>
#include <sstream>
#include <stdexcept>

namespace helfem {
namespace lib1dfem {
namespace polynomial_basis {
namespace detail {

/// Evaluate the n-th derivative w.r.t. x of every HIP2 shape function on
/// the reference element [-1, 1] at the given points x. Three shape
/// functions per node:
///   column 3*fi   = value interpolant h_{i,0}
///   column 3*fi+1 = first-derivative interpolant h_{i,1}
///   column 3*fi+2 = second-derivative interpolant h_{i,2}
/// (Layout matches the GeneralHIPBasis(nder=2) ordering.)
///
/// x0     : node positions (sorted ascending, including endpoints).
/// lipxi  : L_i'(x_i)  for every node i  (precomputed at construction).
/// lipxi2 : L_i''(x_i) for every node i  (ditto).
/// element_length : FE scaling_factor. The derivative interpolants
///                  (3*fi+1 and 3*fi+2) are scaled by element_length^j
///                  so their j-th r-derivative at the node equals 1
///                  in physical units (matches PolynomialBasis::eval_dnf).
///
/// Implemented for n in {0, 1, 2}; higher orders throw -- they're not
/// needed once the Taylor pipeline in RadialBasis has been retired
/// (see PR #69).
template <typename T>
void eval_hip2_prim_dnf(const arma::Col<T> & x, const arma::Col<T> & x0,
                        const arma::Col<T> & lipxi, const arma::Col<T> & lipxi2,
                        arma::Mat<T> & dnf, int n, T element_length) {
  switch (n) {''')


import re
def emit_T_typed(expr):
    """ccode with integer literals wrapped in T(...) so the expression
    compiles at any scalar type T."""
    code = sp.ccode(sp.expand(expr))
    # Replace standalone integers (and integers followed by .0) with T(N).
    code = re.sub(r'(?<![\w.])([0-9]+)(?:\.0)?(?![\w.])', r'T(\1)', code)
    return code


for n in range(3):
    needed_lip_orders = list(range(n + 1))
    print(f'case ({n}): {{')
    print(f'  dnf.zeros(x.n_elem, 3 * x0.n_elem);')
    for k in needed_lip_orders:
        name = ['Lx_all', 'dLx_all', 'ddLx_all'][k]
        print(f'  arma::Mat<T> {name};')
        print(f'  eval_lip_prim_dnf<T>(x, x0, {name}, {k});')
    print(f'  for (size_t ix = 0; ix < x.n_elem; ix++) {{')
    print(f'    for (size_t fi = 0; fi < x0.n_elem; fi++) {{')
    print(f'      const T xv      = x(ix);')
    print(f'      const T xi      = x0(fi);')
    print(f'      const T Lx      = Lx_all(ix, fi);')
    if n >= 1:
        print(f'      const T dLx     = dLx_all(ix, fi);')
    if n >= 2:
        print(f'      const T ddLx    = ddLx_all(ix, fi);')
    print(f'      const T dLxi_v  = lipxi(fi);')
    print(f'      const T ddLxi_v = lipxi2(fi);')
    print(f'      // SymPy-derived closed forms for d^{n}/dx^{n} of each HIP2 shape:')
    for j in range(3):
        print(f'      dnf(ix, 3*fi + {j}) = {emit_T_typed(hpow_deriv(j, n))};')
    print(f'      dnf(ix, 3*fi + 1) *= element_length;')
    print(f'      dnf(ix, 3*fi + 2) *= element_length * element_length;')
    print(f'    }}')
    print(f'  }}')
    print(f'}} break;')


print('default: {')
print('  std::ostringstream oss;')
print('  oss << "HIP2Basis: derivative order " << n')
print('      << " not implemented (only 0, 1, 2 supported).\\n";')
print('  throw std::logic_error(oss.str());')
print('}')
print('  }')
print('}')

print('''
} // namespace detail
} // namespace polynomial_basis
} // namespace lib1dfem
} // namespace helfem

#endif''')
