#
#                This source code is part of
#
#                          HelFEM
#                             -
# Finite element methods for electronic structure calculations on small systems
#
# Written by Susi Lehtola, 2018-
# Copyright (c) 2018- Susi Lehtola
#
# SPDX-License-Identifier: BSD-3-Clause
# See the LICENSE file at the root of this source distribution
# for the full license text.
#
# =====================================================================
# Unified generator for the HIP (Hermite interpolating polynomial)
# family, at ANY order.
#
# Replaces generate_hip_code.py, generate_hip2_code.py and
# generate_hip3_code.py, which were three copies of one construction with
# the order hard-coded, and adds the eval_over_r (1/r) derivation that
# only HIP2 ever had.
#
#   python3 generate_hip_family_code.py --order 1  > ../../lib1dfem/include/lib1dfem/HIPBasis_eval.h
#   python3 generate_hip_family_code.py --order 2  > ../../lib1dfem/include/lib1dfem/HIP2Basis_eval.h
#   python3 generate_hip_family_code.py --order 3  > ../../lib1dfem/include/lib1dfem/HIP3Basis_eval.h
#
# LIP is NOT part of this: it is the PRIMITIVE these are built on. The
# shapes below are expressed in terms of L_i and its derivatives, which
# the LIP evaluator supplies at runtime, so folding LIP in here would be
# circular. generate_lip_code.py stays as it is.
#
# ---------------------------------------------------------------------
# THE CONSTRUCTION
#
# For interpolation order `nder` (nder = 1 -> HIP, 2 -> HIP2, ...) there
# are nder+1 shape functions per node, and
#
#     h_{i,j}(x) = L_i(x)^m * q_j(x - x_i),        m = nder + 1
#
# L_i is the Lagrange polynomial of node i, so L_i has a simple zero at
# every OTHER node; raising it to the power m = nder+1 makes that a zero
# of order nder+1, which kills the value AND the first nder derivatives
# of h at every other node. That is the whole trick -- the shape is
# automatically Hermite-orthogonal to all other nodes, and only node i
# itself needs fixing up.
#
# That fix-up is q_j, a polynomial of degree <= nder in t = x - x_i,
# determined by requiring
#
#     (d^k/dt^k) [ P(t) q_j(t) ] (0) = delta_{jk},   k = 0..nder
#
# with P(t) = L_i(x_i + t)^m. By Leibniz, and writing q_j = sum_a c_a t^a
# (so q_j^{(a)}(0) = a! c_a),
#
#     sum_{a=0..k} C(k,a) * P^{(k-a)}(0) * a! * c_a = delta_{jk}
#
# which is LOWER TRIANGULAR in c (P(0) = L_i(x_i)^m = 1 on the diagonal),
# hence uniquely and trivially solvable. Everything below just does that
# symbolically for arbitrary nder, which is what makes one script cover
# every order.
#
# P^{(r)}(0) is expressed via L_i^{(k)}(x_i) for k <= r -- the values the
# caller precomputes and passes in as lipxi, lipxi2, ... So the derived
# expressions are in terms of runtime quantities, and the generated code
# works for ARBITRARY node positions, exactly as before.
# =====================================================================

import argparse
import re
import sympy as sp

ap = argparse.ArgumentParser(description=__doc__)
ap.add_argument("--order", type=int, required=True,
                help="interpolation order nder (1 = HIP, 2 = HIP2, 3 = HIP3, ...)")
ap.add_argument("--maxderiv", type=int, default=4,
                help="highest derivative order n to emit (default 4). The old "
                     "hand-written HIP2/HIP3 stopped at 2, which was an accident "
                     "of how they were written, not a constraint.")
args = ap.parse_args()

NDER = args.order
MAXD = args.maxderiv
M = NDER + 1                       # power of L_i
NSHAPE = NDER + 1                  # shapes per node

if NDER < 1:
    raise SystemExit("--order must be >= 1; LIP (order 0) is the primitive, "
                     "generated by generate_lip_code.py.")

# Naming that matches the existing headers exactly, so no C++ has to change.
TAG = "hip" if NDER == 1 else f"hip{NDER}"          # eval_hip_prim_dnf, eval_hip2_prim_dnf, ...
CLS = "HIPBasis" if NDER == 1 else f"HIP{NDER}Basis"
GUARD = f"LIB1DFEM_{CLS.upper()}_EVAL_H"

# ---------------------------------------------------------------------
# Symbols. Names match the C++ locals so no rename pass is needed.
# ---------------------------------------------------------------------
xv = sp.Symbol("xv", real=True)          # evaluation point
xi = sp.Symbol("xi", real=True)          # node position x_i
t = xv - xi

# L_i^(k)(xv), k = 0..MAXD   -- supplied at runtime by the LIP evaluator
LX = [sp.Symbol("Lx" if k == 0 else ("dLx" if k == 1 else ("ddLx" if k == 2 else f"d{k}Lx")),
                real=True) for k in range(MAXD + 1)]
# L_i^(k)(x_i), k = 1..NDER  -- precomputed by the basis class (lipxi, lipxi2, ...)
LXI = [None] + [sp.Symbol("dLxi_v" if k == 1 else ("ddLxi_v" if k == 2 else f"d{k}Lxi_v"),
                          real=True) for k in range(1, NDER + 1)]

# ---------------------------------------------------------------------
# P = L_i^m and its x-derivatives, by the chain rule on the SYMBOL Lx.
#
# SymPy cannot differentiate "an unknown function with known derivatives",
# so model L_i as a function of a dummy and substitute the symbols for its
# derivatives afterwards. This is exact, and generalises to any order --
# which the hand-written scripts did NOT (they spelled out the chain rule
# by hand and so were stuck at their order).
# ---------------------------------------------------------------------
_u = sp.Symbol("_u", real=True)
_L = sp.Function("_L")

def deriv_of_L_power(power, n):
    """d^n/dx^n [ L(x)^power ], with L^(k)(x) -> LX[k]."""
    expr = sp.diff(_L(_u) ** power, _u, n)
    for k in range(n, -1, -1):
        expr = expr.subs(sp.Derivative(_L(_u), (_u, k)), LX[k]) if k > 0 else expr.subs(_L(_u), LX[0])
    return sp.expand(expr)

# P^{(r)}(0) at the NODE: same expression, but with L^(k)(x_i):
#   L(x_i) = 1 (Lagrange), L'(x_i) = lipxi, L''(x_i) = lipxi2, ...
def P_deriv_at_node(r):
    expr = sp.diff(_L(_u) ** M, _u, r)
    for k in range(r, -1, -1):
        if k == 0:
            expr = expr.subs(_L(_u), sp.Integer(1))          # L_i(x_i) = 1
        else:
            sub = LXI[k] if k <= NDER else sp.Integer(0)     # higher node derivs not supplied
            expr = expr.subs(sp.Derivative(_L(_u), (_u, k)), sub)
    return sp.expand(expr)

# ---------------------------------------------------------------------
# Solve the triangular system for each q_j.
# ---------------------------------------------------------------------
Pn = [P_deriv_at_node(r) for r in range(NDER + 1)]   # P^{(r)}(0)

q = []
for j in range(NSHAPE):
    c = sp.symbols(f"c0:{NDER+1}")
    eqs = []
    for k in range(NDER + 1):
        lhs = sum(sp.binomial(k, a) * Pn[k - a] * sp.factorial(a) * c[a] for a in range(k + 1))
        eqs.append(sp.Eq(sp.expand(lhs), 1 if k == j else 0))
    sol = sp.solve(eqs, c, dict=True)[0]
    qj = sum(sp.simplify(sol[c[a]]) * t**a for a in range(NDER + 1))
    q.append(sp.expand(qj))

# ---------------------------------------------------------------------
# h_{i,j}^{(n)} = sum_a C(n,a) * (L^m)^{(a)} * q_j^{(n-a)}   (Leibniz)
# ---------------------------------------------------------------------
def shape_deriv(j, n):
    total = 0
    for a in range(n + 1):
        total += sp.binomial(n, a) * deriv_of_L_power(M, a) * sp.diff(q[j], xv, n - a)
    return sp.expand(total)

# ---------------------------------------------------------------------
# C++ emission
# ---------------------------------------------------------------------
def ccode_T(expr):
    """ccode with bare integer literals wrapped in T(...) so the expression
    compiles at any scalar type (double, long double, _Float128)."""
    code = sp.ccode(sp.horner(sp.expand(expr), xv) if expr.free_symbols & {xv} else sp.expand(expr))
    return re.sub(r"(?<![\w.])([0-9]+)(?:\.0)?(?![\w.])", r"T(\1)", code)

def lipxi_params():
    return ", ".join(f"const Vec<T> & {'lipxi' if k == 1 else f'lipxi{k}'}" for k in range(1, NDER + 1))

print(f'''/*
 * This file is autogenerated by libhelfem/src/generate_hip_family_code.py
 *     python3 generate_hip_family_code.py --order {NDER} --maxderiv {MAXD}
 * DO NOT EDIT BY HAND.
 *
 *                This source code is part of
 *                          HelFEM
 *
 * Written by Susi Lehtola, 2018-
 * Copyright (c) 2018- Susi Lehtola
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
#ifndef {GUARD}
#define {GUARD}

#include <lib1dfem/types.h>
#include <lib1dfem/LIPBasis_eval.h>
#include <sstream>
#include <stdexcept>

namespace helfem {{
namespace lib1dfem {{
namespace polynomial_basis {{
namespace detail {{

/// Evaluate the n-th x-derivative of every {CLS} shape function on the
/// reference element [-1, 1]. {NSHAPE} shapes per node:''')
for j in range(NSHAPE):
    kind = "value" if j == 0 else ("first-derivative" if j == 1 else f"{j}-th-derivative")
    print(f"///   column {NSHAPE}*fi{f' + {j}' if j else '    '} = {kind} interpolant h_{{i,{j}}}")
print(f'''///
/// Built as h_{{i,j}}(x) = L_i(x)^{M} * q_j(x - x_i): L_i^{M} has a zero of order
/// {M} at every other node, which annihilates the value and the first {NDER}
/// derivatives there, and q_j (degree <= {NDER}) fixes up node i itself.
///
/// x0     : node positions (sorted ascending, including endpoints).''')
for k in range(1, NDER + 1):
    nm = "lipxi" if k == 1 else f"lipxi{k}"
    print(f"/// {nm:6s} : L_i^({k})(x_i) for every node i (precomputed at construction).")
print(f'''/// element_length : FE scaling_factor. Shape j is scaled by element_length^j
///                  so its j-th r-derivative at the node is 1 in physical
///                  units (matches PolynomialBasis::eval_dnf).
///
/// Derivative orders n = 0..{MAXD} are provided.
template <typename T>
void eval_{TAG}_prim_dnf(const Vec<T> & x, const Vec<T> & x0,
                       {lipxi_params()},
                       Mat<T> & dnf, int n, T element_length) {{
  switch (n) {{''')

for n in range(MAXD + 1):
    print(f"case ({n}): {{")
    print(f"  dnf.setZero((Eigen::Index) x.size(), {NSHAPE} * (Eigen::Index) x0.size());")
    for k in range(n + 1):
        nm = ["Lx_all", "dLx_all", "ddLx_all"][k] if k < 3 else f"d{k}Lx_all"
        print(f"  Mat<T> {nm};")
        print(f"  eval_lip_prim_dnf<T>(x, x0, {nm}, {k});")
    print("  for (size_t ix = 0; ix < (size_t) x.size(); ix++) {")
    print("    for (size_t fi = 0; fi < (size_t) x0.size(); fi++) {")
    print("      const T xv = x(ix);")
    print("      const T xi = x0(fi);")
    for k in range(n + 1):
        nm = ["Lx_all", "dLx_all", "ddLx_all"][k] if k < 3 else f"d{k}Lx_all"
        print(f"      const T {LX[k]} = {nm}(ix, fi);")
    for k in range(1, NDER + 1):
        src = "lipxi" if k == 1 else f"lipxi{k}"
        print(f"      const T {LXI[k]} = {src}(fi);")
    for j in range(NSHAPE):
        print(f"      dnf(ix, {NSHAPE}*fi + {j}) = {ccode_T(shape_deriv(j, n))};")
    for j in range(1, NSHAPE):
        scale = " * ".join(["element_length"] * j)
        print(f"      dnf(ix, {NSHAPE}*fi + {j}) *= {scale};")
    print("    }")
    print("  }")
    print("} break;")

print(f'''default: {{
  std::ostringstream oss;
  oss << "{CLS}: derivative order " << n
      << " not implemented (0..{MAXD} supported).\\n";
  throw std::logic_error(oss.str());
}}
  }}
}}

}} // namespace detail
}} // namespace polynomial_basis
}} // namespace lib1dfem
}} // namespace helfem

#endif''')
