/*
 * This file is autogenerated by libhelfem/src/generate_hip_family_code.py
 *     python3 generate_hip_family_code.py --order 1 --maxderiv 2 --over-r
 * DO NOT EDIT BY HAND.
 *
 *                This source code is part of
 *                          HelFEM
 *
 * Written by Susi Lehtola, 2018-
 * Copyright (c) 2018- Susi Lehtola
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
#ifndef HELFEM_FEM_HIPBASIS_OVER_R_H
#define HELFEM_FEM_HIPBASIS_OVER_R_H

#include <types.h>
#include <LIPBasis_eval.h>
#include <cmath>
#include <sstream>
#include <stdexcept>

namespace helfem {
namespace polynomial_basis {
namespace detail {

/// d^n/dr^n of B_u(r)/r for the surviving HIPBasis shapes on the FIRST element,
/// where r = element_length * (x + 1).
///
/// B/r is 0/0 at x = -1. The Dirichlet BC (drop_first(zero_func=true)) removes
/// the one shape that does not vanish there, so the ratio is finite -- but
/// DIVIDING by r near the origin is catastrophic. The (x+1) factor is deflated
/// analytically instead:
///
///   node 0 (at x = -1): q_j(0) = 0 for the surviving j >= 1, so q_j = t*qtil_j
///       exactly, and  h/(x+1) = L_0^2 * qtil_j.
///
///   node i >= 1: L_i(-1) = 0, so L_i = (x+1) * p_red/(x_i+1), giving
///       h/(x+1) = (x+1)^1 * (p_red/(x_i+1))^2 * q_j,
///       with p_red the Lagrange polynomial of node i over the nodes EXCLUDING
///       node 0 (hence the reduced node vector below).
///
/// Every factor is a polynomial -- nothing cancels -- and the expressions are
/// emitted in factored form for that reason.
///
/// enabled : dummy indices of the surviving shapes (2 per node).
template <typename T>
void eval_hip_prim_over_r(const Vec<T> & x, const Vec<T> & x0,
                       const Vec<T> & lipxi,
                       const IVec & enabled,
                       Mat<T> & dnf_over_r, int n, T element_length) {
  if (n < 0 || n > 2) {
    std::ostringstream oss;
    oss << "HIPBasis::eval_over_r: derivative order " << n
        << " not implemented (0..2 supported).\n";
    throw std::logic_error(oss.str());
  }
  if (enabled.size() == 0)
    throw std::logic_error("HIPBasis::eval_over_r: no surviving basis functions.\n");
  if (enabled(0) == 0)
    throw std::logic_error(
        "HIPBasis::eval_over_r requires drop_first(zero_func=true): the value shape "
        "at node 0 has B(-1) != 0, so B/r is genuinely singular.\n");

  const Vec<T> x0_red = x0.segment(1, x0.size() - 1);

  // Full LIP (column 0 gives L_0) and reduced LIP (p_red for nodes i >= 1).
  Mat<T> Lf[2+1], Lr[2+1];
  for (int k = 0; k <= n; k++) {
    eval_lip_prim_dnf<T>(x, x0,     Lf[k], k);
    eval_lip_prim_dnf<T>(x, x0_red, Lr[k], k);
  }

  dnf_over_r.resize(x.size(), enabled.size());
  for (Eigen::Index c = 0; c < enabled.size(); c++) {
    const Eigen::Index idx  = enabled(c);
    const Eigen::Index node = idx / 2;
    const Eigen::Index kind = idx % 2;

    for (Eigen::Index ix = 0; ix < x.size(); ix++) {
      const T xv = x(ix);
      const T xi = x0(node);
      T R = T(0);

      if (node == 0) {
        const T Lx = Lf[0](ix, 0);
        const T dLx = (n >= 1) ? Lf[1](ix, 0) : T(0);
        const T ddLx = (n >= 2) ? Lf[2](ix, 0) : T(0);
        const T dLxi_v = lipxi(node);
        switch (n) {
        case 0:
          switch (kind) {
          case 1: {
            R = (Lx)*(Lx);
          } break;
          }
          break;
        case 1:
          switch (kind) {
          case 1: {
            R = T(2)*Lx*dLx;
          } break;
          }
          break;
        case 2:
          switch (kind) {
          case 1: {
            R = T(2)*Lx*ddLx + T(2)*(dLx)*(dLx);
          } break;
          }
          break;
        }
      } else {
        const T pr = Lr[0](ix, node - 1);
        const T dpr = (n >= 1) ? Lr[1](ix, node - 1) : T(0);
        const T ddpr = (n >= 2) ? Lr[2](ix, node - 1) : T(0);
        const T dLxi_v = lipxi(node);
        switch (n) {
        case 0:
          switch (kind) {
          case 0: {
            const T cse0 = T(2)*dLxi_v;
            R = (pr)*(pr)*(xv + T(1))*(cse0*xi - cse0*xv + T(1))/std::pow(xi + T(1), T(2));
          } break;
          case 1: {
            R = (pr)*(pr)*(-xi + xv)*(xv + T(1))/std::pow(xi + T(1), T(2));
          } break;
          }
          break;
        case 1:
          switch (kind) {
          case 0: {
            const T cse0 = (pr)*(pr);
            const T cse1 = xv + T(1);
            const T cse2 = T(2)*dLxi_v;
            const T cse3 = cse2*xi - cse2*xv + T(1);
            R = (-cse0*cse1*cse2 + cse0*cse3 + T(2)*cse1*cse3*dpr*pr)/std::pow(xi + T(1), T(2));
          } break;
          case 1: {
            const T cse0 = (pr)*(pr);
            const T cse1 = xv + T(1);
            const T cse2 = -xi + xv;
            R = (cse0*cse1 + cse0*cse2 + T(2)*cse1*cse2*dpr*pr)/std::pow(xi + T(1), T(2));
          } break;
          }
          break;
        case 2:
          switch (kind) {
          case 0: {
            const T cse0 = T(4)*dLxi_v;
            const T cse1 = T(2)*xv;
            const T cse2 = -cse1*dLxi_v + T(2)*dLxi_v*xi + T(1);
            R = (-cse0*dpr*pr*(cse1 + T(2)) - cse0*(pr)*(pr) + T(4)*cse2*dpr*pr + cse2*(xv + T(1))*(T(2)*ddpr*pr + T(2)*(dpr)*(dpr)))/std::pow(xi + T(1), T(2));
          } break;
          case 1: {
            const T cse0 = -xi + xv;
            const T cse1 = T(2)*pr;
            R = (T(4)*cse0*dpr*pr + cse0*(xv + T(1))*(cse1*ddpr + T(2)*(dpr)*(dpr)) + cse1*dpr*(T(2)*xv + T(2)) + T(2)*(pr)*(pr))/std::pow(xi + T(1), T(2));
          } break;
          }
          break;
        }
      }

      // d^n/dr^n [B/r] = e^(kind - 1 - n) * d^n/dx^n [h/(x+1)],
      // the e^kind coming from the derivative-shape scaling and e^(-1-n) from
      // r = e*(x+1) plus the chain rule.
      dnf_over_r(ix, c) = R * std::pow(element_length, (int) kind - 1 - n);
    }
  }
}

} // namespace detail
} // namespace polynomial_basis
} // namespace helfem

#endif
