// Machine-generated by xckernel; do not edit.
// Reproduce with: python -m xckernel.emitters.helfemwriter --emit <file>
// Copyright (c) 2026 Susi Lehtola.
#pragma once
#include <cmath>

namespace helfem {
namespace xckernel {
/* machine-generated by xckernel; do not edit. */
// Ground-state XC potential, gradient channel (GGA and tau-meta-GGA alike).
// One component: the channel depends only on its own component, because
// sigma is a sum of squares, so the caller applies this once per component
// in any coordinate system -- radial, spherical, prolate spheroidal or pure-m.
static inline void xck_helfem_vxc_grad(double grad_rho_r, double vsigma, double & v_r) {
  v_r = 2*grad_rho_r*vsigma;
}

/* machine-generated by xckernel; do not edit. */
// Spin-resolved ground-state XC potential, gradient channel.
// Polarized Libxc arrays keep their flat packing (vsigma_0 = aa, _1 = ab, _2 = bb).
static inline void xck_helfem_vxc_grad_spin(double grad_rho_a_r, double grad_rho_b_r, double vsigma_0, double vsigma_1, double vsigma_2, double & v_a_r, double & v_b_r) {
  v_a_r = 2*grad_rho_a_r*vsigma_0 + grad_rho_b_r*vsigma_1;
  v_b_r = grad_rho_a_r*vsigma_1 + 2*grad_rho_b_r*vsigma_2;
}

/* machine-generated by xckernel; do not edit. */
// lda fxc coefficient channels, one radial gradient component.
// u multiplies the basis-function pair, v_r its radial derivative,
// w_tau (tau families) the pair's kinetic-energy density.
static inline void xck_helfem_fxc_lda(double rho_p1, double v2rho2, double & u) {
  u = rho_p1*v2rho2;
}

/* machine-generated by xckernel; do not edit. */
// Spin-resolved lda fxc channels, one radial gradient component.
// u_s multiplies the basis-function pair of spin s, v_s_r its radial derivative,
// w_s (tau families) the pair's kinetic-energy density.
// Polarized Libxc arrays keep their flat packing (v2rho2_0 = uu, _1 = ud, _2 = dd, ...).
static inline void xck_helfem_fxc_lda_spin(double rho_a_p1, double rho_b_p1, double v2rho2_0, double v2rho2_1, double v2rho2_2, double & u_a, double & u_b) {
  u_a = rho_a_p1*v2rho2_0 + rho_b_p1*v2rho2_1;
  u_b = rho_a_p1*v2rho2_1 + rho_b_p1*v2rho2_2;
}

/* machine-generated by xckernel; do not edit. */
// gga fxc coefficient channels, one radial gradient component.
// u multiplies the basis-function pair, v_r its radial derivative,
// w_tau (tau families) the pair's kinetic-energy density.
static inline void xck_helfem_fxc_gga(double grad_rho_p1_r, double grad_rho_r, double rho_p1, double v2rho2, double v2rhosigma, double v2sigma2, double vsigma, double & u, double & v_r) {
  const double t0 = grad_rho_r*v2rhosigma;
  const double t1 = 2*grad_rho_p1_r;
  u = rho_p1*v2rho2 + t0*t1;
  v_r = 2*grad_rho_p1_r*vsigma + 2*grad_rho_r*grad_rho_r*t1*v2sigma2 + 2*rho_p1*t0;
}

/* machine-generated by xckernel; do not edit. */
// Spin-resolved gga fxc channels, one radial gradient component.
// u_s multiplies the basis-function pair of spin s, v_s_r its radial derivative,
// w_s (tau families) the pair's kinetic-energy density.
// Polarized Libxc arrays keep their flat packing (v2rho2_0 = uu, _1 = ud, _2 = dd, ...).
static inline void xck_helfem_fxc_gga_spin(double grad_rho_a_p1_r, double grad_rho_a_r, double grad_rho_b_p1_r, double grad_rho_b_r, double rho_a_p1, double rho_b_p1, double v2rho2_0, double v2rho2_1, double v2rho2_2, double v2rhosigma_0, double v2rhosigma_1, double v2rhosigma_2, double v2rhosigma_3, double v2rhosigma_4, double v2rhosigma_5, double v2sigma2_0, double v2sigma2_1, double v2sigma2_2, double v2sigma2_3, double v2sigma2_4, double v2sigma2_5, double vsigma_0, double vsigma_1, double vsigma_2, double & u_a, double & v_a_r, double & u_b, double & v_b_r) {
  const double t0 = grad_rho_b_r*v2rhosigma_1;
  const double t1 = grad_rho_a_r*grad_rho_b_p1_r;
  const double t2 = 2*grad_rho_a_p1_r;
  const double t3 = grad_rho_a_r*t2;
  const double t4 = 2*grad_rho_b_p1_r;
  const double t5 = grad_rho_b_r*t4;
  const double t6 = grad_rho_b_r*v2rhosigma_4;
  const double t7 = grad_rho_a_r*rho_a_p1;
  const double t8 = grad_rho_a_r*rho_b_p1;
  const double t9 = grad_rho_b_r*t1;
  const double t10 = grad_rho_b_r*grad_rho_b_r;
  const double t11 = grad_rho_a_p1_r*v2sigma2_3;
  const double t12 = 4*grad_rho_a_p1_r;
  const double t13 = grad_rho_a_r*grad_rho_b_r;
  const double t14 = t12*t13;
  const double t15 = 4*t9;
  const double t16 = grad_rho_a_r*grad_rho_a_r;
  const double t17 = t16*v2sigma2_1;
  const double t18 = t10*v2sigma2_4;
  const double t19 = 2*grad_rho_b_r;
  u_a = grad_rho_a_p1_r*t0 + rho_a_p1*v2rho2_0 + rho_b_p1*v2rho2_1 + t1*v2rhosigma_1 + t3*v2rhosigma_0 + t5*v2rhosigma_2;
  v_a_r = grad_rho_b_p1_r*vsigma_1 + rho_a_p1*t0 + rho_b_p1*t6 + t10*t11 + t12*t16*v2sigma2_0 + t14*v2sigma2_1 + t15*v2sigma2_2 + t17*t4 + t18*t4 + t2*vsigma_0 + 2*t7*v2rhosigma_0 + 2*t8*v2rhosigma_3 + t9*v2sigma2_3;
  u_b = grad_rho_a_p1_r*t6 + rho_a_p1*v2rho2_1 + rho_b_p1*v2rho2_2 + t1*v2rhosigma_4 + t3*v2rhosigma_3 + t5*v2rhosigma_5;
  v_b_r = grad_rho_a_p1_r*vsigma_1 + 4*grad_rho_b_p1_r*t10*v2sigma2_5 + grad_rho_b_p1_r*t16*v2sigma2_3 + rho_a_p1*t19*v2rhosigma_2 + rho_b_p1*t19*v2rhosigma_5 + t11*t13 + t14*v2sigma2_2 + t15*v2sigma2_4 + t17*t2 + t18*t2 + t4*vsigma_2 + t7*v2rhosigma_1 + t8*v2rhosigma_4;
}

/* machine-generated by xckernel; do not edit. */
// gga fxc coefficient channels, two gradient components (mu, nu).
// The pure-m density is phi-independent, so the azimuthal component is absent
// rather than zero: it is never formed.
static inline void xck_helfem_fxc_gga_2d(double grad_rho_p1_mu, double grad_rho_p1_nu, double grad_rho_mu, double grad_rho_nu, double rho_p1, double v2rho2, double v2rhosigma, double v2sigma2, double vsigma, double & u, double & v_mu, double & v_nu) {
  const double t0 = 2*v2rhosigma;
  const double t1 = grad_rho_mu*grad_rho_p1_mu;
  const double t2 = grad_rho_nu*grad_rho_p1_nu;
  const double t3 = rho_p1*v2rhosigma;
  const double t4 = 2*v2sigma2;
  u = rho_p1*v2rho2 + t0*t1 + t0*t2;
  v_mu = 2*grad_rho_mu*grad_rho_mu*grad_rho_p1_mu*t4 + 2*grad_rho_mu*t2*t4 + 2*grad_rho_mu*t3 + 2*grad_rho_p1_mu*vsigma;
  v_nu = 2*grad_rho_nu*grad_rho_nu*grad_rho_p1_nu*t4 + 2*grad_rho_nu*t1*t4 + 2*grad_rho_nu*t3 + 2*grad_rho_p1_nu*vsigma;
}

/* machine-generated by xckernel; do not edit. */
// Spin-resolved gga fxc channels, two gradient components (mu, nu).
// Polarized Libxc arrays keep their flat packing (v2rho2_0 = uu, _1 = ud, _2 = dd, ...).
static inline void xck_helfem_fxc_gga_2d_spin(double grad_rho_a_p1_mu, double grad_rho_a_p1_nu, double grad_rho_a_mu, double grad_rho_a_nu, double grad_rho_b_p1_mu, double grad_rho_b_p1_nu, double grad_rho_b_mu, double grad_rho_b_nu, double rho_a_p1, double rho_b_p1, double v2rho2_0, double v2rho2_1, double v2rho2_2, double v2rhosigma_0, double v2rhosigma_1, double v2rhosigma_2, double v2rhosigma_3, double v2rhosigma_4, double v2rhosigma_5, double v2sigma2_0, double v2sigma2_1, double v2sigma2_2, double v2sigma2_3, double v2sigma2_4, double v2sigma2_5, double vsigma_0, double vsigma_1, double vsigma_2, double & u_a, double & v_a_mu, double & v_a_nu, double & u_b, double & v_b_mu, double & v_b_nu) {
  const double t0 = grad_rho_a_mu*grad_rho_b_p1_mu;
  const double t1 = grad_rho_a_nu*grad_rho_b_p1_nu;
  const double t2 = grad_rho_b_mu*v2rhosigma_1;
  const double t3 = grad_rho_b_nu*v2rhosigma_1;
  const double t4 = 2*v2rhosigma_0;
  const double t5 = grad_rho_a_mu*grad_rho_a_p1_mu;
  const double t6 = grad_rho_a_nu*t4;
  const double t7 = 2*v2rhosigma_2;
  const double t8 = grad_rho_b_mu*grad_rho_b_p1_mu;
  const double t9 = grad_rho_b_nu*grad_rho_b_p1_nu;
  const double t10 = 2*vsigma_0;
  const double t11 = rho_b_p1*v2rhosigma_4;
  const double t12 = 2*v2rhosigma_3;
  const double t13 = rho_b_p1*t12;
  const double t14 = grad_rho_b_mu*v2sigma2_3;
  const double t15 = grad_rho_a_p1_nu*v2sigma2_3;
  const double t16 = grad_rho_b_mu*grad_rho_b_nu;
  const double t17 = grad_rho_b_mu*grad_rho_b_mu;
  const double t18 = grad_rho_a_p1_mu*v2sigma2_3;
  const double t19 = 4*v2sigma2_0;
  const double t20 = grad_rho_a_nu*grad_rho_a_p1_nu;
  const double t21 = 2*v2sigma2_1;
  const double t22 = grad_rho_a_mu*t1;
  const double t23 = grad_rho_a_p1_mu*grad_rho_b_mu;
  const double t24 = 4*grad_rho_a_mu;
  const double t25 = t23*t24;
  const double t26 = grad_rho_a_p1_nu*grad_rho_b_nu;
  const double t27 = grad_rho_a_mu*t21;
  const double t28 = 4*v2sigma2_2;
  const double t29 = grad_rho_b_mu*t0;
  const double t30 = grad_rho_b_mu*t20;
  const double t31 = 2*v2sigma2_4;
  const double t32 = t31*t9;
  const double t33 = grad_rho_a_mu*grad_rho_a_mu;
  const double t34 = grad_rho_a_p1_mu*t33;
  const double t35 = grad_rho_b_p1_mu*t33;
  const double t36 = grad_rho_b_p1_mu*t17;
  const double t37 = grad_rho_b_nu*v2sigma2_3;
  const double t38 = grad_rho_b_nu*grad_rho_b_nu;
  const double t39 = grad_rho_a_nu*t0;
  const double t40 = t21*t5;
  const double t41 = grad_rho_a_nu*t26;
  const double t42 = grad_rho_a_nu*t8;
  const double t43 = grad_rho_b_nu*t28;
  const double t44 = grad_rho_b_nu*t31;
  const double t45 = grad_rho_a_nu*grad_rho_a_nu;
  const double t46 = grad_rho_a_p1_nu*t45;
  const double t47 = grad_rho_b_p1_nu*t45;
  const double t48 = t31*t38;
  const double t49 = 2*v2rhosigma_5;
  const double t50 = 2*vsigma_2;
  const double t51 = rho_a_p1*v2rhosigma_1;
  const double t52 = rho_a_p1*t7;
  const double t53 = rho_b_p1*t49;
  const double t54 = grad_rho_b_mu*t18;
  const double t55 = grad_rho_b_nu*t15;
  const double t56 = 4*v2sigma2_4;
  const double t57 = grad_rho_b_mu*t31;
  const double t58 = 4*v2sigma2_5;
  u_a = grad_rho_a_p1_mu*t2 + grad_rho_a_p1_nu*t3 + grad_rho_a_p1_nu*t6 + rho_a_p1*v2rho2_0 + rho_b_p1*v2rho2_1 + t0*v2rhosigma_1 + t1*v2rhosigma_1 + t4*t5 + t7*t8 + t7*t9;
  v_a_mu = grad_rho_a_mu*rho_a_p1*t4 + grad_rho_a_mu*t13 + grad_rho_a_mu*t19*t20 + grad_rho_a_p1_mu*t10 + grad_rho_b_mu*t11 + grad_rho_b_mu*t32 + grad_rho_b_p1_mu*vsigma_1 + rho_a_p1*t2 + t0*t14 + t1*t14 + t15*t16 + t17*t18 + t19*t34 + t21*t22 + t21*t30 + t21*t35 + t24*t9*v2sigma2_2 + t25*v2sigma2_1 + t26*t27 + t28*t29 + t31*t36;
  v_a_nu = grad_rho_a_nu*t13 + grad_rho_a_nu*t19*t5 + grad_rho_a_nu*t21*t23 + grad_rho_a_p1_nu*t10 + grad_rho_b_nu*t11 + grad_rho_b_nu*t40 + grad_rho_b_p1_nu*t48 + grad_rho_b_p1_nu*vsigma_1 + rho_a_p1*t3 + rho_a_p1*t6 + t0*t37 + t1*t37 + t1*t43 + t15*t38 + t16*t18 + t19*t46 + t21*t39 + t21*t47 + t28*t42 + 4*t41*v2sigma2_1 + t44*t8;
  u_b = rho_a_p1*v2rho2_1 + rho_b_p1*v2rho2_2 + t0*v2rhosigma_4 + t1*v2rhosigma_4 + t12*t20 + t12*t5 + t23*v2rhosigma_4 + t26*v2rhosigma_4 + t49*t8 + t49*t9;
  v_b_mu = grad_rho_a_mu*t11 + grad_rho_a_mu*t32 + grad_rho_a_mu*t51 + grad_rho_a_mu*t54 + grad_rho_a_mu*t55 + grad_rho_a_p1_mu*t17*t31 + grad_rho_a_p1_mu*vsigma_1 + grad_rho_b_mu*t52 + grad_rho_b_mu*t53 + grad_rho_b_mu*t58*t9 + grad_rho_b_p1_mu*t50 + t1*t57 + t20*t27 + t21*t34 + t22*v2sigma2_3 + t25*v2sigma2_2 + t26*t57 + t28*t30 + t29*t56 + t35*v2sigma2_3 + t36*t58;
  v_b_nu = grad_rho_a_nu*t11 + grad_rho_a_nu*t40 + grad_rho_a_nu*t51 + grad_rho_a_nu*t54 + grad_rho_a_nu*t55 + grad_rho_a_p1_nu*t48 + grad_rho_a_p1_nu*vsigma_1 + grad_rho_b_nu*t1*t56 + grad_rho_b_nu*t52 + grad_rho_b_nu*t53 + grad_rho_b_nu*t58*t8 + grad_rho_b_p1_nu*t38*t58 + grad_rho_b_p1_nu*t50 + t0*t44 + t21*t46 + t23*t44 + t28*t41 + t31*t42 + t39*v2sigma2_3 + t43*t5 + t47*v2sigma2_3;
}

/* machine-generated by xckernel; do not edit. */
// gga fxc coefficient channels, three gradient components.
static inline void xck_helfem_fxc_gga_3d(double grad_rho_p1_x, double grad_rho_p1_y, double grad_rho_p1_z, double grad_rho_x, double grad_rho_y, double grad_rho_z, double rho_p1, double v2rho2, double v2rhosigma, double v2sigma2, double vsigma, double & u, double & v_x, double & v_y, double & v_z) {
  const double t0 = 2*v2rhosigma;
  const double t1 = grad_rho_p1_x*grad_rho_x;
  const double t2 = grad_rho_p1_y*grad_rho_y;
  const double t3 = grad_rho_p1_z*grad_rho_z;
  const double t4 = rho_p1*v2rhosigma;
  const double t5 = 2*v2sigma2;
  const double t6 = grad_rho_x*t5;
  const double t7 = grad_rho_y*t5;
  const double t8 = grad_rho_z*t5;
  u = rho_p1*v2rho2 + t0*t1 + t0*t2 + t0*t3;
  v_x = 2*grad_rho_p1_x*grad_rho_x*grad_rho_x*t5 + 2*grad_rho_p1_x*vsigma + 2*grad_rho_x*t4 + 2*t2*t6 + 2*t3*t6;
  v_y = 2*grad_rho_p1_y*grad_rho_y*grad_rho_y*t5 + 2*grad_rho_p1_y*vsigma + 2*grad_rho_y*t4 + 2*t1*t7 + 2*t3*t7;
  v_z = 2*grad_rho_p1_z*grad_rho_z*grad_rho_z*t5 + 2*grad_rho_p1_z*vsigma + 2*grad_rho_z*t4 + 2*t1*t8 + 2*t2*t8;
}

/* machine-generated by xckernel; do not edit. */
// Spin-resolved gga fxc channels, three gradient components.
// Polarized Libxc arrays keep their flat packing (v2rho2_0 = uu, _1 = ud, _2 = dd, ...).
static inline void xck_helfem_fxc_gga_3d_spin(double grad_rho_a_p1_x, double grad_rho_a_p1_y, double grad_rho_a_p1_z, double grad_rho_a_x, double grad_rho_a_y, double grad_rho_a_z, double grad_rho_b_p1_x, double grad_rho_b_p1_y, double grad_rho_b_p1_z, double grad_rho_b_x, double grad_rho_b_y, double grad_rho_b_z, double rho_a_p1, double rho_b_p1, double v2rho2_0, double v2rho2_1, double v2rho2_2, double v2rhosigma_0, double v2rhosigma_1, double v2rhosigma_2, double v2rhosigma_3, double v2rhosigma_4, double v2rhosigma_5, double v2sigma2_0, double v2sigma2_1, double v2sigma2_2, double v2sigma2_3, double v2sigma2_4, double v2sigma2_5, double vsigma_0, double vsigma_1, double vsigma_2, double & u_a, double & v_a_x, double & v_a_y, double & v_a_z, double & u_b, double & v_b_x, double & v_b_y, double & v_b_z) {
  const double t0 = grad_rho_b_x*v2rhosigma_1;
  const double t1 = grad_rho_b_y*v2rhosigma_1;
  const double t2 = grad_rho_b_z*v2rhosigma_1;
  const double t3 = grad_rho_a_x*grad_rho_b_p1_x;
  const double t4 = grad_rho_a_y*grad_rho_b_p1_y;
  const double t5 = grad_rho_a_z*grad_rho_b_p1_z;
  const double t6 = 2*v2rhosigma_0;
  const double t7 = grad_rho_a_p1_x*grad_rho_a_x;
  const double t8 = grad_rho_a_y*t6;
  const double t9 = grad_rho_a_z*t6;
  const double t10 = 2*v2rhosigma_2;
  const double t11 = grad_rho_b_p1_x*grad_rho_b_x;
  const double t12 = grad_rho_b_p1_y*grad_rho_b_y;
  const double t13 = grad_rho_b_p1_z*grad_rho_b_z;
  const double t14 = 2*vsigma_0;
  const double t15 = rho_b_p1*v2rhosigma_4;
  const double t16 = 2*v2rhosigma_3;
  const double t17 = rho_b_p1*t16;
  const double t18 = grad_rho_a_p1_y*v2sigma2_3;
  const double t19 = grad_rho_b_x*grad_rho_b_y;
  const double t20 = grad_rho_a_p1_z*v2sigma2_3;
  const double t21 = grad_rho_b_z*t20;
  const double t22 = grad_rho_b_x*v2sigma2_3;
  const double t23 = grad_rho_b_x*grad_rho_b_x;
  const double t24 = grad_rho_a_p1_x*v2sigma2_3;
  const double t25 = grad_rho_a_p1_x*grad_rho_b_x;
  const double t26 = 4*grad_rho_a_x;
  const double t27 = t25*t26;
  const double t28 = grad_rho_a_p1_y*grad_rho_a_y;
  const double t29 = 4*v2sigma2_0;
  const double t30 = grad_rho_a_x*t29;
  const double t31 = grad_rho_a_p1_y*grad_rho_b_y;
  const double t32 = 2*v2sigma2_1;
  const double t33 = grad_rho_a_x*t32;
  const double t34 = grad_rho_b_x*t32;
  const double t35 = grad_rho_a_p1_z*grad_rho_a_z;
  const double t36 = grad_rho_a_p1_z*grad_rho_b_z;
  const double t37 = 4*v2sigma2_2;
  const double t38 = grad_rho_b_x*t37;
  const double t39 = t26*v2sigma2_2;
  const double t40 = 2*v2sigma2_4;
  const double t41 = grad_rho_b_x*t40;
  const double t42 = grad_rho_a_x*grad_rho_a_x;
  const double t43 = grad_rho_a_p1_x*t42;
  const double t44 = grad_rho_b_p1_x*t42;
  const double t45 = grad_rho_b_p1_x*t23;
  const double t46 = grad_rho_b_y*v2sigma2_3;
  const double t47 = grad_rho_b_y*grad_rho_b_y;
  const double t48 = grad_rho_a_y*t29;
  const double t49 = grad_rho_b_y*t32;
  const double t50 = grad_rho_a_y*t32;
  const double t51 = 4*v2sigma2_1;
  const double t52 = grad_rho_a_y*t31;
  const double t53 = grad_rho_a_y*t37;
  const double t54 = grad_rho_b_y*t37;
  const double t55 = grad_rho_b_y*t40;
  const double t56 = grad_rho_a_y*grad_rho_a_y;
  const double t57 = grad_rho_a_p1_y*t56;
  const double t58 = grad_rho_b_p1_y*t56;
  const double t59 = t40*t47;
  const double t60 = grad_rho_b_x*t24;
  const double t61 = grad_rho_b_y*t18;
  const double t62 = grad_rho_b_z*v2sigma2_3;
  const double t63 = grad_rho_b_z*grad_rho_b_z;
  const double t64 = grad_rho_a_z*t29;
  const double t65 = grad_rho_b_z*t32;
  const double t66 = grad_rho_a_z*t32;
  const double t67 = grad_rho_a_z*t36;
  const double t68 = grad_rho_a_z*t37;
  const double t69 = grad_rho_b_z*t37;
  const double t70 = grad_rho_b_z*t40;
  const double t71 = grad_rho_a_z*grad_rho_a_z;
  const double t72 = grad_rho_a_p1_z*t71;
  const double t73 = grad_rho_b_p1_z*t71;
  const double t74 = t40*t63;
  const double t75 = 2*v2rhosigma_5;
  const double t76 = 2*vsigma_2;
  const double t77 = rho_a_p1*v2rhosigma_1;
  const double t78 = rho_a_p1*t10;
  const double t79 = rho_b_p1*t75;
  const double t80 = grad_rho_a_x*v2sigma2_3;
  const double t81 = 4*v2sigma2_4;
  const double t82 = grad_rho_a_x*t40;
  const double t83 = 4*v2sigma2_5;
  const double t84 = grad_rho_b_x*t83;
  const double t85 = grad_rho_a_y*v2sigma2_3;
  const double t86 = grad_rho_a_y*t40;
  const double t87 = grad_rho_b_y*t83;
  const double t88 = grad_rho_a_z*v2sigma2_3;
  const double t89 = grad_rho_a_z*t40;
  const double t90 = grad_rho_b_z*t83;
  u_a = grad_rho_a_p1_x*t0 + grad_rho_a_p1_y*t1 + grad_rho_a_p1_y*t8 + grad_rho_a_p1_z*t2 + grad_rho_a_p1_z*t9 + rho_a_p1*v2rho2_0 + rho_b_p1*v2rho2_1 + t10*t11 + t10*t12 + t10*t13 + t3*v2rhosigma_1 + t4*v2rhosigma_1 + t5*v2rhosigma_1 + t6*t7;
  v_a_x = grad_rho_a_p1_x*t14 + grad_rho_a_x*rho_a_p1*t6 + grad_rho_a_x*t17 + grad_rho_b_p1_x*vsigma_1 + grad_rho_b_x*t15 + grad_rho_b_x*t21 + rho_a_p1*t0 + t12*t39 + t12*t41 + t13*t39 + t13*t41 + t18*t19 + t22*t3 + t22*t4 + t22*t5 + t23*t24 + t27*v2sigma2_1 + t28*t30 + t28*t34 + t29*t43 + t3*t38 + t30*t35 + t31*t33 + t32*t44 + t33*t36 + t33*t4 + t33*t5 + t34*t35 + t40*t45;
  v_a_y = grad_rho_a_p1_y*t14 + grad_rho_a_y*t17 + grad_rho_b_p1_y*t59 + grad_rho_b_p1_y*vsigma_1 + grad_rho_b_y*t15 + grad_rho_b_y*t21 + rho_a_p1*t1 + rho_a_p1*t8 + t11*t53 + t11*t55 + t13*t53 + t13*t55 + t18*t47 + t19*t24 + t25*t50 + t29*t57 + t3*t46 + t3*t50 + t32*t58 + t35*t48 + t35*t49 + t36*t50 + t4*t46 + t4*t54 + t46*t5 + t48*t7 + t49*t7 + t5*t50 + t51*t52;
  v_a_z = grad_rho_a_p1_z*t14 + grad_rho_a_z*t17 + grad_rho_b_p1_z*t74 + grad_rho_b_p1_z*vsigma_1 + grad_rho_b_z*t15 + grad_rho_b_z*t60 + grad_rho_b_z*t61 + rho_a_p1*t2 + rho_a_p1*t9 + t11*t68 + t11*t70 + t12*t68 + t12*t70 + t20*t63 + t25*t66 + t28*t64 + t28*t65 + t29*t72 + t3*t62 + t3*t66 + t31*t66 + t32*t73 + t4*t62 + t4*t66 + t5*t62 + t5*t69 + t51*t67 + t64*t7 + t65*t7;
  u_b = rho_a_p1*v2rho2_1 + rho_b_p1*v2rho2_2 + t11*t75 + t12*t75 + t13*t75 + t16*t28 + t16*t35 + t16*t7 + t25*v2rhosigma_4 + t3*v2rhosigma_4 + t31*v2rhosigma_4 + t36*v2rhosigma_4 + t4*v2rhosigma_4 + t5*v2rhosigma_4;
  v_b_x = grad_rho_a_p1_x*t23*t40 + grad_rho_a_p1_x*vsigma_1 + grad_rho_a_x*t15 + grad_rho_a_x*t21 + grad_rho_a_x*t60 + grad_rho_a_x*t61 + grad_rho_a_x*t77 + grad_rho_b_p1_x*t76 + grad_rho_b_x*t3*t81 + grad_rho_b_x*t78 + grad_rho_b_x*t79 + t12*t82 + t12*t84 + t13*t82 + t13*t84 + t27*v2sigma2_2 + t28*t33 + t28*t38 + t31*t41 + t32*t43 + t33*t35 + t35*t38 + t36*t41 + t4*t41 + t4*t80 + t41*t5 + t44*v2sigma2_3 + t45*t83 + t5*t80;
  v_b_y = grad_rho_a_p1_y*t59 + grad_rho_a_p1_y*vsigma_1 + grad_rho_a_y*t15 + grad_rho_a_y*t21 + grad_rho_a_y*t60 + grad_rho_a_y*t61 + grad_rho_a_y*t77 + grad_rho_b_p1_y*t47*t83 + grad_rho_b_p1_y*t76 + grad_rho_b_y*t4*t81 + grad_rho_b_y*t78 + grad_rho_b_y*t79 + t11*t86 + t11*t87 + t13*t86 + t13*t87 + t25*t55 + t3*t55 + t3*t85 + t32*t57 + t35*t50 + t35*t54 + t36*t55 + t37*t52 + t5*t55 + t5*t85 + t50*t7 + t54*t7 + t58*v2sigma2_3;
  v_b_z = grad_rho_a_p1_z*t74 + grad_rho_a_p1_z*vsigma_1 + grad_rho_a_z*t15 + grad_rho_a_z*t21 + grad_rho_a_z*t60 + grad_rho_a_z*t61 + grad_rho_a_z*t77 + grad_rho_b_p1_z*t63*t83 + grad_rho_b_p1_z*t76 + grad_rho_b_z*t5*t81 + grad_rho_b_z*t78 + grad_rho_b_z*t79 + t11*t89 + t11*t90 + t12*t89 + t12*t90 + t25*t70 + t28*t66 + t28*t69 + t3*t70 + t3*t88 + t31*t70 + t32*t72 + t37*t67 + t4*t70 + t4*t88 + t66*t7 + t69*t7 + t73*v2sigma2_3;
}

/* machine-generated by xckernel; do not edit. */
// mgga_tau fxc coefficient channels, one radial gradient component.
// u multiplies the basis-function pair, v_r its radial derivative,
// w_tau (tau families) the pair's kinetic-energy density.
static inline void xck_helfem_fxc_mgga_tau(double grad_rho_p1_r, double grad_rho_r, double rho_p1, double tau_p1, double v2rho2, double v2rhosigma, double v2rhotau, double v2sigma2, double v2sigmatau, double v2tau2, double vsigma, double & u, double & v_r, double & w_tau) {
  const double t0 = grad_rho_r*v2rhosigma;
  const double t1 = 2*grad_rho_p1_r;
  const double t2 = grad_rho_r*v2sigmatau;
  u = rho_p1*v2rho2 + t0*t1 + tau_p1*v2rhotau;
  v_r = 2*grad_rho_p1_r*vsigma + 2*grad_rho_r*grad_rho_r*t1*v2sigma2 + 2*rho_p1*t0 + 2*t2*tau_p1;
  w_tau = rho_p1*v2rhotau + t1*t2 + tau_p1*v2tau2;
}

/* machine-generated by xckernel; do not edit. */
// Spin-resolved mgga_tau fxc channels, one radial gradient component.
// u_s multiplies the basis-function pair of spin s, v_s_r its radial derivative,
// w_s (tau families) the pair's kinetic-energy density.
// Polarized Libxc arrays keep their flat packing (v2rho2_0 = uu, _1 = ud, _2 = dd, ...).
static inline void xck_helfem_fxc_mgga_tau_spin(double grad_rho_a_p1_r, double grad_rho_a_r, double grad_rho_b_p1_r, double grad_rho_b_r, double rho_a_p1, double rho_b_p1, double tau_a_p1, double tau_b_p1, double v2rho2_0, double v2rho2_1, double v2rho2_2, double v2rhosigma_0, double v2rhosigma_1, double v2rhosigma_2, double v2rhosigma_3, double v2rhosigma_4, double v2rhosigma_5, double v2rhotau_0, double v2rhotau_1, double v2rhotau_2, double v2rhotau_3, double v2sigma2_0, double v2sigma2_1, double v2sigma2_2, double v2sigma2_3, double v2sigma2_4, double v2sigma2_5, double v2sigmatau_0, double v2sigmatau_1, double v2sigmatau_2, double v2sigmatau_3, double v2sigmatau_4, double v2sigmatau_5, double v2tau2_0, double v2tau2_1, double v2tau2_2, double vsigma_0, double vsigma_1, double vsigma_2, double & u_a, double & v_a_r, double & w_a, double & u_b, double & v_b_r, double & w_b) {
  const double t0 = grad_rho_b_r*v2rhosigma_1;
  const double t1 = grad_rho_a_r*grad_rho_b_p1_r;
  const double t2 = 2*grad_rho_a_p1_r;
  const double t3 = grad_rho_a_r*t2;
  const double t4 = 2*grad_rho_b_p1_r;
  const double t5 = grad_rho_b_r*t4;
  const double t6 = grad_rho_b_r*v2rhosigma_4;
  const double t7 = grad_rho_b_r*v2sigmatau_2;
  const double t8 = tau_b_p1*v2sigmatau_3;
  const double t9 = grad_rho_a_r*rho_a_p1;
  const double t10 = grad_rho_a_r*rho_b_p1;
  const double t11 = grad_rho_a_r*tau_a_p1;
  const double t12 = 2*tau_b_p1;
  const double t13 = grad_rho_b_r*t1;
  const double t14 = grad_rho_b_r*grad_rho_b_r;
  const double t15 = grad_rho_a_p1_r*v2sigma2_3;
  const double t16 = grad_rho_a_p1_r*grad_rho_b_r;
  const double t17 = 4*grad_rho_a_r*t16;
  const double t18 = 4*t13;
  const double t19 = grad_rho_a_r*grad_rho_a_r;
  const double t20 = t19*v2sigma2_1;
  const double t21 = t14*v2sigma2_4;
  const double t22 = 2*grad_rho_b_r;
  u_a = grad_rho_a_p1_r*t0 + rho_a_p1*v2rho2_0 + rho_b_p1*v2rho2_1 + t1*v2rhosigma_1 + t3*v2rhosigma_0 + t5*v2rhosigma_2 + tau_a_p1*v2rhotau_0 + tau_b_p1*v2rhotau_1;
  v_a_r = 4*grad_rho_a_p1_r*t19*v2sigma2_0 + grad_rho_a_r*t12*v2sigmatau_1 + grad_rho_b_p1_r*vsigma_1 + grad_rho_b_r*t8 + rho_a_p1*t0 + rho_b_p1*t6 + 2*t10*v2rhosigma_3 + 2*t11*v2sigmatau_0 + t13*v2sigma2_3 + t14*t15 + t17*v2sigma2_1 + t18*v2sigma2_2 + t2*vsigma_0 + t20*t4 + t21*t4 + t7*tau_a_p1 + 2*t9*v2rhosigma_0;
  w_a = grad_rho_a_p1_r*t7 + rho_a_p1*v2rhotau_0 + rho_b_p1*v2rhotau_2 + t1*v2sigmatau_2 + t3*v2sigmatau_0 + t5*v2sigmatau_4 + tau_a_p1*v2tau2_0 + tau_b_p1*v2tau2_1;
  u_b = grad_rho_a_p1_r*t6 + rho_a_p1*v2rho2_1 + rho_b_p1*v2rho2_2 + t1*v2rhosigma_4 + t3*v2rhosigma_3 + t5*v2rhosigma_5 + tau_a_p1*v2rhotau_2 + tau_b_p1*v2rhotau_3;
  v_b_r = grad_rho_a_p1_r*vsigma_1 + grad_rho_a_r*grad_rho_b_r*t15 + grad_rho_a_r*t8 + 4*grad_rho_b_p1_r*t14*v2sigma2_5 + grad_rho_b_p1_r*t19*v2sigma2_3 + grad_rho_b_r*t12*v2sigmatau_5 + rho_a_p1*t22*v2rhosigma_2 + rho_b_p1*t22*v2rhosigma_5 + t10*v2rhosigma_4 + t11*v2sigmatau_2 + t17*v2sigma2_2 + t18*v2sigma2_4 + t2*t20 + t2*t21 + t22*tau_a_p1*v2sigmatau_4 + t4*vsigma_2 + t9*v2rhosigma_1;
  w_b = rho_a_p1*v2rhotau_1 + rho_b_p1*v2rhotau_3 + t1*v2sigmatau_3 + t16*v2sigmatau_3 + t3*v2sigmatau_1 + t5*v2sigmatau_5 + tau_a_p1*v2tau2_1 + tau_b_p1*v2tau2_2;
}

/* machine-generated by xckernel; do not edit. */
// mgga_tau fxc coefficient channels, two gradient components (mu, nu).
// The pure-m density is phi-independent, so the azimuthal component is absent
// rather than zero: it is never formed.
static inline void xck_helfem_fxc_mgga_tau_2d(double grad_rho_p1_mu, double grad_rho_p1_nu, double grad_rho_mu, double grad_rho_nu, double rho_p1, double tau_p1, double v2rho2, double v2rhosigma, double v2rhotau, double v2sigma2, double v2sigmatau, double v2tau2, double vsigma, double & u, double & v_mu, double & v_nu, double & w_tau) {
  const double t0 = 2*v2rhosigma;
  const double t1 = grad_rho_mu*grad_rho_p1_mu;
  const double t2 = grad_rho_nu*grad_rho_p1_nu;
  const double t3 = rho_p1*v2rhosigma;
  const double t4 = tau_p1*v2sigmatau;
  const double t5 = 2*v2sigma2;
  const double t6 = 2*v2sigmatau;
  u = rho_p1*v2rho2 + t0*t1 + t0*t2 + tau_p1*v2rhotau;
  v_mu = 2*grad_rho_mu*grad_rho_mu*grad_rho_p1_mu*t5 + 2*grad_rho_mu*t2*t5 + 2*grad_rho_mu*t3 + 2*grad_rho_mu*t4 + 2*grad_rho_p1_mu*vsigma;
  v_nu = 2*grad_rho_nu*grad_rho_nu*grad_rho_p1_nu*t5 + 2*grad_rho_nu*t1*t5 + 2*grad_rho_nu*t3 + 2*grad_rho_nu*t4 + 2*grad_rho_p1_nu*vsigma;
  w_tau = rho_p1*v2rhotau + t1*t6 + t2*t6 + tau_p1*v2tau2;
}

/* machine-generated by xckernel; do not edit. */
// Spin-resolved mgga_tau fxc channels, two gradient components (mu, nu).
// Polarized Libxc arrays keep their flat packing (v2rho2_0 = uu, _1 = ud, _2 = dd, ...).
static inline void xck_helfem_fxc_mgga_tau_2d_spin(double grad_rho_a_p1_mu, double grad_rho_a_p1_nu, double grad_rho_a_mu, double grad_rho_a_nu, double grad_rho_b_p1_mu, double grad_rho_b_p1_nu, double grad_rho_b_mu, double grad_rho_b_nu, double rho_a_p1, double rho_b_p1, double tau_a_p1, double tau_b_p1, double v2rho2_0, double v2rho2_1, double v2rho2_2, double v2rhosigma_0, double v2rhosigma_1, double v2rhosigma_2, double v2rhosigma_3, double v2rhosigma_4, double v2rhosigma_5, double v2rhotau_0, double v2rhotau_1, double v2rhotau_2, double v2rhotau_3, double v2sigma2_0, double v2sigma2_1, double v2sigma2_2, double v2sigma2_3, double v2sigma2_4, double v2sigma2_5, double v2sigmatau_0, double v2sigmatau_1, double v2sigmatau_2, double v2sigmatau_3, double v2sigmatau_4, double v2sigmatau_5, double v2tau2_0, double v2tau2_1, double v2tau2_2, double vsigma_0, double vsigma_1, double vsigma_2, double & u_a, double & v_a_mu, double & v_a_nu, double & w_a, double & u_b, double & v_b_mu, double & v_b_nu, double & w_b) {
  const double t0 = grad_rho_a_mu*grad_rho_b_p1_mu;
  const double t1 = grad_rho_a_nu*grad_rho_b_p1_nu;
  const double t2 = grad_rho_b_mu*v2rhosigma_1;
  const double t3 = grad_rho_b_nu*v2rhosigma_1;
  const double t4 = 2*v2rhosigma_0;
  const double t5 = grad_rho_a_mu*grad_rho_a_p1_mu;
  const double t6 = grad_rho_a_nu*t4;
  const double t7 = 2*v2rhosigma_2;
  const double t8 = grad_rho_b_mu*grad_rho_b_p1_mu;
  const double t9 = grad_rho_b_nu*grad_rho_b_p1_nu;
  const double t10 = 2*vsigma_0;
  const double t11 = rho_b_p1*v2rhosigma_4;
  const double t12 = tau_a_p1*v2sigmatau_2;
  const double t13 = tau_b_p1*v2sigmatau_3;
  const double t14 = 2*grad_rho_a_mu;
  const double t15 = rho_b_p1*v2rhosigma_3;
  const double t16 = tau_a_p1*v2sigmatau_0;
  const double t17 = tau_b_p1*v2sigmatau_1;
  const double t18 = grad_rho_b_mu*v2sigma2_3;
  const double t19 = grad_rho_a_p1_nu*v2sigma2_3;
  const double t20 = grad_rho_b_mu*grad_rho_b_nu;
  const double t21 = grad_rho_b_mu*grad_rho_b_mu;
  const double t22 = grad_rho_a_p1_mu*v2sigma2_3;
  const double t23 = 4*v2sigma2_0;
  const double t24 = grad_rho_a_nu*grad_rho_a_p1_nu;
  const double t25 = t14*v2sigma2_1;
  const double t26 = grad_rho_a_p1_mu*grad_rho_b_mu;
  const double t27 = 4*grad_rho_a_mu;
  const double t28 = t26*t27;
  const double t29 = grad_rho_a_p1_nu*grad_rho_b_nu;
  const double t30 = 4*v2sigma2_2;
  const double t31 = grad_rho_b_mu*t0;
  const double t32 = 2*v2sigma2_1;
  const double t33 = grad_rho_b_mu*t24;
  const double t34 = 2*v2sigma2_4;
  const double t35 = grad_rho_b_mu*t34;
  const double t36 = grad_rho_a_mu*grad_rho_a_mu;
  const double t37 = grad_rho_a_p1_mu*t36;
  const double t38 = grad_rho_b_p1_mu*t36;
  const double t39 = grad_rho_b_p1_mu*t21;
  const double t40 = 2*grad_rho_a_nu;
  const double t41 = grad_rho_b_nu*v2sigma2_3;
  const double t42 = grad_rho_b_nu*grad_rho_b_nu;
  const double t43 = grad_rho_a_nu*t0;
  const double t44 = t32*t5;
  const double t45 = grad_rho_a_nu*t29;
  const double t46 = grad_rho_a_nu*t8;
  const double t47 = grad_rho_b_nu*t30;
  const double t48 = grad_rho_b_nu*t34;
  const double t49 = grad_rho_a_nu*grad_rho_a_nu;
  const double t50 = grad_rho_a_p1_nu*t49;
  const double t51 = grad_rho_b_p1_nu*t49;
  const double t52 = t34*t42;
  const double t53 = 2*t5;
  const double t54 = grad_rho_a_p1_nu*t40;
  const double t55 = 2*v2sigmatau_4;
  const double t56 = 2*v2rhosigma_5;
  const double t57 = 2*vsigma_2;
  const double t58 = rho_a_p1*v2rhosigma_1;
  const double t59 = rho_a_p1*t7;
  const double t60 = rho_b_p1*t56;
  const double t61 = t55*tau_a_p1;
  const double t62 = 2*v2sigmatau_5;
  const double t63 = t62*tau_b_p1;
  const double t64 = grad_rho_b_mu*t22;
  const double t65 = grad_rho_b_nu*t19;
  const double t66 = 4*v2sigma2_4;
  const double t67 = 4*v2sigma2_5;
  u_a = grad_rho_a_p1_mu*t2 + grad_rho_a_p1_nu*t3 + grad_rho_a_p1_nu*t6 + rho_a_p1*v2rho2_0 + rho_b_p1*v2rho2_1 + t0*v2rhosigma_1 + t1*v2rhosigma_1 + t4*t5 + t7*t8 + t7*t9 + tau_a_p1*v2rhotau_0 + tau_b_p1*v2rhotau_1;
  v_a_mu = grad_rho_a_mu*rho_a_p1*t4 + grad_rho_a_mu*t23*t24 + grad_rho_a_p1_mu*t10 + grad_rho_b_mu*t11 + grad_rho_b_mu*t12 + grad_rho_b_mu*t13 + grad_rho_b_p1_mu*vsigma_1 + rho_a_p1*t2 + t0*t18 + t1*t18 + t1*t25 + t14*t15 + t14*t16 + t14*t17 + t19*t20 + t21*t22 + t23*t37 + t25*t29 + t27*t9*v2sigma2_2 + t28*v2sigma2_1 + t30*t31 + t32*t33 + t32*t38 + t34*t39 + t35*t9;
  v_a_nu = grad_rho_a_nu*t23*t5 + grad_rho_a_nu*t26*t32 + grad_rho_a_p1_nu*t10 + grad_rho_b_nu*t11 + grad_rho_b_nu*t12 + grad_rho_b_nu*t13 + grad_rho_b_nu*t44 + grad_rho_b_p1_nu*t52 + grad_rho_b_p1_nu*vsigma_1 + rho_a_p1*t3 + rho_a_p1*t6 + t0*t41 + t1*t41 + t1*t47 + t15*t40 + t16*t40 + t17*t40 + t19*t42 + t20*t22 + t23*t50 + t30*t46 + t32*t43 + t32*t51 + 4*t45*v2sigma2_1 + t48*t8;
  w_a = rho_a_p1*v2rhotau_0 + rho_b_p1*v2rhotau_2 + t0*v2sigmatau_2 + t1*v2sigmatau_2 + t26*v2sigmatau_2 + t29*v2sigmatau_2 + t53*v2sigmatau_0 + t54*v2sigmatau_0 + t55*t8 + t55*t9 + tau_a_p1*v2tau2_0 + tau_b_p1*v2tau2_1;
  u_b = rho_a_p1*v2rho2_1 + rho_b_p1*v2rho2_2 + t0*v2rhosigma_4 + t1*v2rhosigma_4 + t26*v2rhosigma_4 + t29*v2rhosigma_4 + t53*v2rhosigma_3 + t54*v2rhosigma_3 + t56*t8 + t56*t9 + tau_a_p1*v2rhotau_2 + tau_b_p1*v2rhotau_3;
  v_b_mu = grad_rho_a_mu*t1*v2sigma2_3 + grad_rho_a_mu*t11 + grad_rho_a_mu*t12 + grad_rho_a_mu*t13 + grad_rho_a_mu*t58 + grad_rho_a_mu*t64 + grad_rho_a_mu*t65 + grad_rho_a_p1_mu*t21*t34 + grad_rho_a_p1_mu*vsigma_1 + grad_rho_b_mu*t59 + grad_rho_b_mu*t60 + grad_rho_b_mu*t61 + grad_rho_b_mu*t63 + grad_rho_b_mu*t67*t9 + grad_rho_b_p1_mu*t57 + t1*t35 + t14*t9*v2sigma2_4 + t24*t25 + t28*v2sigma2_2 + t29*t35 + t30*t33 + t31*t66 + t32*t37 + t38*v2sigma2_3 + t39*t67;
  v_b_nu = grad_rho_a_nu*t11 + grad_rho_a_nu*t12 + grad_rho_a_nu*t13 + grad_rho_a_nu*t44 + grad_rho_a_nu*t58 + grad_rho_a_nu*t64 + grad_rho_a_nu*t65 + grad_rho_a_p1_nu*t52 + grad_rho_a_p1_nu*vsigma_1 + grad_rho_b_nu*t1*t66 + grad_rho_b_nu*t59 + grad_rho_b_nu*t60 + grad_rho_b_nu*t61 + grad_rho_b_nu*t63 + grad_rho_b_nu*t67*t8 + grad_rho_b_p1_nu*t42*t67 + grad_rho_b_p1_nu*t57 + t0*t48 + t26*t48 + t30*t45 + t32*t50 + t34*t46 + t43*v2sigma2_3 + t47*t5 + t51*v2sigma2_3;
  w_b = rho_a_p1*v2rhotau_1 + rho_b_p1*v2rhotau_3 + t0*v2sigmatau_3 + t1*v2sigmatau_3 + t26*v2sigmatau_3 + t29*v2sigmatau_3 + t53*v2sigmatau_1 + t54*v2sigmatau_1 + t62*t8 + t62*t9 + tau_a_p1*v2tau2_1 + tau_b_p1*v2tau2_2;
}

/* machine-generated by xckernel; do not edit. */
// mgga_tau fxc coefficient channels, three gradient components.
static inline void xck_helfem_fxc_mgga_tau_3d(double grad_rho_p1_x, double grad_rho_p1_y, double grad_rho_p1_z, double grad_rho_x, double grad_rho_y, double grad_rho_z, double rho_p1, double tau_p1, double v2rho2, double v2rhosigma, double v2rhotau, double v2sigma2, double v2sigmatau, double v2tau2, double vsigma, double & u, double & v_x, double & v_y, double & v_z, double & w_tau) {
  const double t0 = 2*v2rhosigma;
  const double t1 = grad_rho_p1_x*grad_rho_x;
  const double t2 = grad_rho_p1_y*grad_rho_y;
  const double t3 = grad_rho_p1_z*grad_rho_z;
  const double t4 = rho_p1*v2rhosigma;
  const double t5 = tau_p1*v2sigmatau;
  const double t6 = 2*v2sigma2;
  const double t7 = grad_rho_x*t6;
  const double t8 = grad_rho_y*t6;
  const double t9 = grad_rho_z*t6;
  const double t10 = 2*v2sigmatau;
  u = rho_p1*v2rho2 + t0*t1 + t0*t2 + t0*t3 + tau_p1*v2rhotau;
  v_x = 2*grad_rho_p1_x*grad_rho_x*grad_rho_x*t6 + 2*grad_rho_p1_x*vsigma + 2*grad_rho_x*t4 + 2*grad_rho_x*t5 + 2*t2*t7 + 2*t3*t7;
  v_y = 2*grad_rho_p1_y*grad_rho_y*grad_rho_y*t6 + 2*grad_rho_p1_y*vsigma + 2*grad_rho_y*t4 + 2*grad_rho_y*t5 + 2*t1*t8 + 2*t3*t8;
  v_z = 2*grad_rho_p1_z*grad_rho_z*grad_rho_z*t6 + 2*grad_rho_p1_z*vsigma + 2*grad_rho_z*t4 + 2*grad_rho_z*t5 + 2*t1*t9 + 2*t2*t9;
  w_tau = rho_p1*v2rhotau + t1*t10 + t10*t2 + t10*t3 + tau_p1*v2tau2;
}

/* machine-generated by xckernel; do not edit. */
// Spin-resolved mgga_tau fxc channels, three gradient components.
// Polarized Libxc arrays keep their flat packing (v2rho2_0 = uu, _1 = ud, _2 = dd, ...).
static inline void xck_helfem_fxc_mgga_tau_3d_spin(double grad_rho_a_p1_x, double grad_rho_a_p1_y, double grad_rho_a_p1_z, double grad_rho_a_x, double grad_rho_a_y, double grad_rho_a_z, double grad_rho_b_p1_x, double grad_rho_b_p1_y, double grad_rho_b_p1_z, double grad_rho_b_x, double grad_rho_b_y, double grad_rho_b_z, double rho_a_p1, double rho_b_p1, double tau_a_p1, double tau_b_p1, double v2rho2_0, double v2rho2_1, double v2rho2_2, double v2rhosigma_0, double v2rhosigma_1, double v2rhosigma_2, double v2rhosigma_3, double v2rhosigma_4, double v2rhosigma_5, double v2rhotau_0, double v2rhotau_1, double v2rhotau_2, double v2rhotau_3, double v2sigma2_0, double v2sigma2_1, double v2sigma2_2, double v2sigma2_3, double v2sigma2_4, double v2sigma2_5, double v2sigmatau_0, double v2sigmatau_1, double v2sigmatau_2, double v2sigmatau_3, double v2sigmatau_4, double v2sigmatau_5, double v2tau2_0, double v2tau2_1, double v2tau2_2, double vsigma_0, double vsigma_1, double vsigma_2, double & u_a, double & v_a_x, double & v_a_y, double & v_a_z, double & w_a, double & u_b, double & v_b_x, double & v_b_y, double & v_b_z, double & w_b) {
  const double t0 = grad_rho_b_x*v2rhosigma_1;
  const double t1 = grad_rho_b_y*v2rhosigma_1;
  const double t2 = grad_rho_b_z*v2rhosigma_1;
  const double t3 = grad_rho_a_x*grad_rho_b_p1_x;
  const double t4 = grad_rho_a_y*grad_rho_b_p1_y;
  const double t5 = grad_rho_a_z*grad_rho_b_p1_z;
  const double t6 = 2*v2rhosigma_0;
  const double t7 = grad_rho_a_p1_x*grad_rho_a_x;
  const double t8 = grad_rho_a_y*t6;
  const double t9 = grad_rho_a_z*t6;
  const double t10 = 2*v2rhosigma_2;
  const double t11 = grad_rho_b_p1_x*grad_rho_b_x;
  const double t12 = grad_rho_b_p1_y*grad_rho_b_y;
  const double t13 = grad_rho_b_p1_z*grad_rho_b_z;
  const double t14 = 2*vsigma_0;
  const double t15 = rho_b_p1*v2rhosigma_4;
  const double t16 = tau_a_p1*v2sigmatau_2;
  const double t17 = tau_b_p1*v2sigmatau_3;
  const double t18 = 2*grad_rho_a_x;
  const double t19 = rho_b_p1*v2rhosigma_3;
  const double t20 = tau_a_p1*v2sigmatau_0;
  const double t21 = tau_b_p1*v2sigmatau_1;
  const double t22 = grad_rho_a_p1_y*v2sigma2_3;
  const double t23 = grad_rho_b_x*grad_rho_b_y;
  const double t24 = grad_rho_a_p1_z*v2sigma2_3;
  const double t25 = grad_rho_b_z*t24;
  const double t26 = grad_rho_b_x*v2sigma2_3;
  const double t27 = grad_rho_b_x*grad_rho_b_x;
  const double t28 = grad_rho_a_p1_x*v2sigma2_3;
  const double t29 = grad_rho_a_p1_x*grad_rho_b_x;
  const double t30 = 4*grad_rho_a_x;
  const double t31 = t29*t30;
  const double t32 = grad_rho_a_p1_y*grad_rho_a_y;
  const double t33 = 4*v2sigma2_0;
  const double t34 = grad_rho_a_x*t33;
  const double t35 = grad_rho_a_p1_y*grad_rho_b_y;
  const double t36 = t18*v2sigma2_1;
  const double t37 = 2*v2sigma2_1;
  const double t38 = grad_rho_b_x*t37;
  const double t39 = grad_rho_a_p1_z*grad_rho_a_z;
  const double t40 = grad_rho_a_p1_z*grad_rho_b_z;
  const double t41 = 4*v2sigma2_2;
  const double t42 = grad_rho_b_x*t41;
  const double t43 = t30*v2sigma2_2;
  const double t44 = 2*v2sigma2_4;
  const double t45 = grad_rho_b_x*t44;
  const double t46 = grad_rho_a_x*grad_rho_a_x;
  const double t47 = grad_rho_a_p1_x*t46;
  const double t48 = grad_rho_b_p1_x*t46;
  const double t49 = grad_rho_b_p1_x*t27;
  const double t50 = 2*grad_rho_a_y;
  const double t51 = grad_rho_b_y*v2sigma2_3;
  const double t52 = grad_rho_b_y*grad_rho_b_y;
  const double t53 = grad_rho_a_y*t33;
  const double t54 = grad_rho_b_y*t37;
  const double t55 = grad_rho_a_y*t37;
  const double t56 = 4*v2sigma2_1;
  const double t57 = grad_rho_a_y*t35;
  const double t58 = grad_rho_a_y*t41;
  const double t59 = grad_rho_b_y*t41;
  const double t60 = grad_rho_b_y*t44;
  const double t61 = grad_rho_a_y*grad_rho_a_y;
  const double t62 = grad_rho_a_p1_y*t61;
  const double t63 = grad_rho_b_p1_y*t61;
  const double t64 = t44*t52;
  const double t65 = 2*grad_rho_a_z;
  const double t66 = grad_rho_b_x*t28;
  const double t67 = grad_rho_b_y*t22;
  const double t68 = grad_rho_b_z*v2sigma2_3;
  const double t69 = grad_rho_b_z*grad_rho_b_z;
  const double t70 = grad_rho_a_z*t33;
  const double t71 = grad_rho_b_z*t37;
  const double t72 = grad_rho_a_z*t37;
  const double t73 = grad_rho_a_z*t40;
  const double t74 = grad_rho_a_z*t41;
  const double t75 = grad_rho_b_z*t41;
  const double t76 = grad_rho_b_z*t44;
  const double t77 = grad_rho_a_z*grad_rho_a_z;
  const double t78 = grad_rho_a_p1_z*t77;
  const double t79 = grad_rho_b_p1_z*t77;
  const double t80 = t44*t69;
  const double t81 = 2*t7;
  const double t82 = grad_rho_a_p1_y*t50;
  const double t83 = grad_rho_a_p1_z*t65;
  const double t84 = 2*v2sigmatau_4;
  const double t85 = 2*v2rhosigma_5;
  const double t86 = 2*vsigma_2;
  const double t87 = rho_a_p1*v2rhosigma_1;
  const double t88 = rho_a_p1*t10;
  const double t89 = rho_b_p1*t85;
  const double t90 = t84*tau_a_p1;
  const double t91 = 2*v2sigmatau_5;
  const double t92 = t91*tau_b_p1;
  const double t93 = grad_rho_a_x*v2sigma2_3;
  const double t94 = 4*v2sigma2_4;
  const double t95 = t18*v2sigma2_4;
  const double t96 = 4*v2sigma2_5;
  const double t97 = grad_rho_b_x*t96;
  const double t98 = grad_rho_a_y*v2sigma2_3;
  const double t99 = grad_rho_a_y*t44;
  const double t100 = grad_rho_b_y*t96;
  const double t101 = grad_rho_a_z*v2sigma2_3;
  const double t102 = grad_rho_a_z*t44;
  const double t103 = grad_rho_b_z*t96;
  u_a = grad_rho_a_p1_x*t0 + grad_rho_a_p1_y*t1 + grad_rho_a_p1_y*t8 + grad_rho_a_p1_z*t2 + grad_rho_a_p1_z*t9 + rho_a_p1*v2rho2_0 + rho_b_p1*v2rho2_1 + t10*t11 + t10*t12 + t10*t13 + t3*v2rhosigma_1 + t4*v2rhosigma_1 + t5*v2rhosigma_1 + t6*t7 + tau_a_p1*v2rhotau_0 + tau_b_p1*v2rhotau_1;
  v_a_x = grad_rho_a_p1_x*t14 + grad_rho_a_x*rho_a_p1*t6 + grad_rho_b_p1_x*vsigma_1 + grad_rho_b_x*t15 + grad_rho_b_x*t16 + grad_rho_b_x*t17 + grad_rho_b_x*t25 + rho_a_p1*t0 + t12*t43 + t12*t45 + t13*t43 + t13*t45 + t18*t19 + t18*t20 + t18*t21 + t22*t23 + t26*t3 + t26*t4 + t26*t5 + t27*t28 + t3*t42 + t31*v2sigma2_1 + t32*t34 + t32*t38 + t33*t47 + t34*t39 + t35*t36 + t36*t4 + t36*t40 + t36*t5 + t37*t48 + t38*t39 + t44*t49;
  v_a_y = grad_rho_a_p1_y*t14 + grad_rho_b_p1_y*t64 + grad_rho_b_p1_y*vsigma_1 + grad_rho_b_y*t15 + grad_rho_b_y*t16 + grad_rho_b_y*t17 + grad_rho_b_y*t25 + rho_a_p1*t1 + rho_a_p1*t8 + t11*t58 + t11*t60 + t13*t58 + t13*t60 + t19*t50 + t20*t50 + t21*t50 + t22*t52 + t23*t28 + t29*t55 + t3*t51 + t3*t55 + t33*t62 + t37*t63 + t39*t53 + t39*t54 + t4*t51 + t4*t59 + t40*t55 + t5*t51 + t5*t55 + t53*t7 + t54*t7 + t56*t57;
  v_a_z = grad_rho_a_p1_z*t14 + grad_rho_b_p1_z*t80 + grad_rho_b_p1_z*vsigma_1 + grad_rho_b_z*t15 + grad_rho_b_z*t16 + grad_rho_b_z*t17 + grad_rho_b_z*t66 + grad_rho_b_z*t67 + rho_a_p1*t2 + rho_a_p1*t9 + t11*t74 + t11*t76 + t12*t74 + t12*t76 + t19*t65 + t20*t65 + t21*t65 + t24*t69 + t29*t72 + t3*t68 + t3*t72 + t32*t70 + t32*t71 + t33*t78 + t35*t72 + t37*t79 + t4*t68 + t4*t72 + t5*t68 + t5*t75 + t56*t73 + t7*t70 + t7*t71;
  w_a = rho_a_p1*v2rhotau_0 + rho_b_p1*v2rhotau_2 + t11*t84 + t12*t84 + t13*t84 + t29*v2sigmatau_2 + t3*v2sigmatau_2 + t35*v2sigmatau_2 + t4*v2sigmatau_2 + t40*v2sigmatau_2 + t5*v2sigmatau_2 + t81*v2sigmatau_0 + t82*v2sigmatau_0 + t83*v2sigmatau_0 + tau_a_p1*v2tau2_0 + tau_b_p1*v2tau2_1;
  u_b = rho_a_p1*v2rho2_1 + rho_b_p1*v2rho2_2 + t11*t85 + t12*t85 + t13*t85 + t29*v2rhosigma_4 + t3*v2rhosigma_4 + t35*v2rhosigma_4 + t4*v2rhosigma_4 + t40*v2rhosigma_4 + t5*v2rhosigma_4 + t81*v2rhosigma_3 + t82*v2rhosigma_3 + t83*v2rhosigma_3 + tau_a_p1*v2rhotau_2 + tau_b_p1*v2rhotau_3;
  v_b_x = grad_rho_a_p1_x*t27*t44 + grad_rho_a_p1_x*vsigma_1 + grad_rho_a_x*t15 + grad_rho_a_x*t16 + grad_rho_a_x*t17 + grad_rho_a_x*t25 + grad_rho_a_x*t66 + grad_rho_a_x*t67 + grad_rho_a_x*t87 + grad_rho_b_p1_x*t86 + grad_rho_b_x*t3*t94 + grad_rho_b_x*t88 + grad_rho_b_x*t89 + grad_rho_b_x*t90 + grad_rho_b_x*t92 + t12*t95 + t12*t97 + t13*t95 + t13*t97 + t31*v2sigma2_2 + t32*t36 + t32*t42 + t35*t45 + t36*t39 + t37*t47 + t39*t42 + t4*t45 + t4*t93 + t40*t45 + t45*t5 + t48*v2sigma2_3 + t49*t96 + t5*t93;
  v_b_y = grad_rho_a_p1_y*t64 + grad_rho_a_p1_y*vsigma_1 + grad_rho_a_y*t15 + grad_rho_a_y*t16 + grad_rho_a_y*t17 + grad_rho_a_y*t25 + grad_rho_a_y*t66 + grad_rho_a_y*t67 + grad_rho_a_y*t87 + grad_rho_b_p1_y*t52*t96 + grad_rho_b_p1_y*t86 + grad_rho_b_y*t4*t94 + grad_rho_b_y*t88 + grad_rho_b_y*t89 + grad_rho_b_y*t90 + grad_rho_b_y*t92 + t100*t11 + t100*t13 + t11*t99 + t13*t99 + t29*t60 + t3*t60 + t3*t98 + t37*t62 + t39*t55 + t39*t59 + t40*t60 + t41*t57 + t5*t60 + t5*t98 + t55*t7 + t59*t7 + t63*v2sigma2_3;
  v_b_z = grad_rho_a_p1_z*t80 + grad_rho_a_p1_z*vsigma_1 + grad_rho_a_z*t15 + grad_rho_a_z*t16 + grad_rho_a_z*t17 + grad_rho_a_z*t25 + grad_rho_a_z*t66 + grad_rho_a_z*t67 + grad_rho_a_z*t87 + grad_rho_b_p1_z*t69*t96 + grad_rho_b_p1_z*t86 + grad_rho_b_z*t5*t94 + grad_rho_b_z*t88 + grad_rho_b_z*t89 + grad_rho_b_z*t90 + grad_rho_b_z*t92 + t101*t3 + t101*t4 + t102*t11 + t102*t12 + t103*t11 + t103*t12 + t29*t76 + t3*t76 + t32*t72 + t32*t75 + t35*t76 + t37*t78 + t4*t76 + t41*t73 + t7*t72 + t7*t75 + t79*v2sigma2_3;
  w_b = rho_a_p1*v2rhotau_1 + rho_b_p1*v2rhotau_3 + t11*t91 + t12*t91 + t13*t91 + t29*v2sigmatau_3 + t3*v2sigmatau_3 + t35*v2sigmatau_3 + t4*v2sigmatau_3 + t40*v2sigmatau_3 + t5*v2sigmatau_3 + t81*v2sigmatau_1 + t82*v2sigmatau_1 + t83*v2sigmatau_1 + tau_a_p1*v2tau2_1 + tau_b_p1*v2tau2_2;
}
} // namespace xckernel
} // namespace helfem
