// Machine-generated by xckernel; do not edit.
// Reproduce with: python -m xckernel.emitters.helfemwriter --emit <file>
// Copyright (c) 2026 Susi Lehtola.
#pragma once
#include <cmath>

namespace helfem {
namespace xckernel {
/* machine-generated by xckernel; do not edit. */
// Ground-state XC potential, gradient channel (GGA and tau-meta-GGA alike).
// One component: the channel depends only on its own component, because
// sigma is a sum of squares, so the caller applies this once per component
// in any coordinate system -- radial, spherical, prolate spheroidal or pure-m.
static inline void xck_helfem_vxc_grad(double grad_rho_r, double vsigma, double & v_r) {
  v_r = 2*grad_rho_r*vsigma;
}

/* machine-generated by xckernel; do not edit. */
// Spin-resolved ground-state XC potential, gradient channel.
// Polarized Libxc arrays keep their flat packing (vsigma_0 = aa, _1 = ab, _2 = bb).
static inline void xck_helfem_vxc_grad_spin(double grad_rho_a_r, double grad_rho_b_r, double vsigma_0, double vsigma_1, double vsigma_2, double & v_a_r, double & v_b_r) {
  v_a_r = 2*grad_rho_a_r*vsigma_0 + grad_rho_b_r*vsigma_1;
  v_b_r = grad_rho_a_r*vsigma_1 + 2*grad_rho_b_r*vsigma_2;
}

/* machine-generated by xckernel; do not edit. */
// lda fxc coefficient channels, one radial gradient component.
// u multiplies the basis-function pair, v_r its radial derivative,
// w_tau (tau families) the pair's kinetic-energy density.
static inline void xck_helfem_fxc_lda(double rho_p1, double v2rho2, double & u) {
  u = rho_p1*v2rho2;
}

/* machine-generated by xckernel; do not edit. */
// Spin-resolved lda fxc channels, one radial gradient component.
// u_s multiplies the basis-function pair of spin s, v_s_r its radial derivative,
// w_s (tau families) the pair's kinetic-energy density.
// Polarized Libxc arrays keep their flat packing (v2rho2_0 = uu, _1 = ud, _2 = dd, ...).
static inline void xck_helfem_fxc_lda_spin(double rho_a_p1, double rho_b_p1, double v2rho2_0, double v2rho2_1, double v2rho2_2, double & u_a, double & u_b) {
  u_a = rho_a_p1*v2rho2_0 + rho_b_p1*v2rho2_1;
  u_b = rho_a_p1*v2rho2_1 + rho_b_p1*v2rho2_2;
}

/* machine-generated by xckernel; do not edit. */
// gga fxc coefficient channels, one radial gradient component.
// u multiplies the basis-function pair, v_r its radial derivative,
// w_tau (tau families) the pair's kinetic-energy density.
static inline void xck_helfem_fxc_gga(double grad_rho_p1_r, double grad_rho_r, double rho_p1, double v2rho2, double v2rhosigma, double v2sigma2, double vsigma, double & u, double & v_r) {
  const double t0 = grad_rho_r*v2rhosigma;
  const double t1 = 2*grad_rho_p1_r;
  u = rho_p1*v2rho2 + t0*t1;
  v_r = 2*grad_rho_p1_r*vsigma + 2*grad_rho_r*grad_rho_r*t1*v2sigma2 + 2*rho_p1*t0;
}

/* machine-generated by xckernel; do not edit. */
// Spin-resolved gga fxc channels, one radial gradient component.
// u_s multiplies the basis-function pair of spin s, v_s_r its radial derivative,
// w_s (tau families) the pair's kinetic-energy density.
// Polarized Libxc arrays keep their flat packing (v2rho2_0 = uu, _1 = ud, _2 = dd, ...).
static inline void xck_helfem_fxc_gga_spin(double grad_rho_a_p1_r, double grad_rho_a_r, double grad_rho_b_p1_r, double grad_rho_b_r, double rho_a_p1, double rho_b_p1, double v2rho2_0, double v2rho2_1, double v2rho2_2, double v2rhosigma_0, double v2rhosigma_1, double v2rhosigma_2, double v2rhosigma_3, double v2rhosigma_4, double v2rhosigma_5, double v2sigma2_0, double v2sigma2_1, double v2sigma2_2, double v2sigma2_3, double v2sigma2_4, double v2sigma2_5, double vsigma_0, double vsigma_1, double vsigma_2, double & u_a, double & v_a_r, double & u_b, double & v_b_r) {
  const double t0 = grad_rho_b_r*v2rhosigma_1;
  const double t1 = grad_rho_a_r*grad_rho_b_p1_r;
  const double t2 = 2*grad_rho_a_p1_r;
  const double t3 = grad_rho_a_r*t2;
  const double t4 = 2*grad_rho_b_p1_r;
  const double t5 = grad_rho_b_r*t4;
  const double t6 = grad_rho_b_r*v2rhosigma_4;
  const double t7 = grad_rho_a_r*rho_a_p1;
  const double t8 = grad_rho_a_r*rho_b_p1;
  const double t9 = grad_rho_b_r*t1;
  const double t10 = grad_rho_b_r*grad_rho_b_r;
  const double t11 = grad_rho_a_p1_r*v2sigma2_3;
  const double t12 = 4*grad_rho_a_p1_r;
  const double t13 = grad_rho_a_r*grad_rho_b_r;
  const double t14 = t12*t13;
  const double t15 = 4*t9;
  const double t16 = grad_rho_a_r*grad_rho_a_r;
  const double t17 = t16*v2sigma2_1;
  const double t18 = t10*v2sigma2_4;
  const double t19 = 2*grad_rho_b_r;
  u_a = grad_rho_a_p1_r*t0 + rho_a_p1*v2rho2_0 + rho_b_p1*v2rho2_1 + t1*v2rhosigma_1 + t3*v2rhosigma_0 + t5*v2rhosigma_2;
  v_a_r = grad_rho_b_p1_r*vsigma_1 + rho_a_p1*t0 + rho_b_p1*t6 + t10*t11 + t12*t16*v2sigma2_0 + t14*v2sigma2_1 + t15*v2sigma2_2 + t17*t4 + t18*t4 + t2*vsigma_0 + 2*t7*v2rhosigma_0 + 2*t8*v2rhosigma_3 + t9*v2sigma2_3;
  u_b = grad_rho_a_p1_r*t6 + rho_a_p1*v2rho2_1 + rho_b_p1*v2rho2_2 + t1*v2rhosigma_4 + t3*v2rhosigma_3 + t5*v2rhosigma_5;
  v_b_r = grad_rho_a_p1_r*vsigma_1 + 4*grad_rho_b_p1_r*t10*v2sigma2_5 + grad_rho_b_p1_r*t16*v2sigma2_3 + rho_a_p1*t19*v2rhosigma_2 + rho_b_p1*t19*v2rhosigma_5 + t11*t13 + t14*v2sigma2_2 + t15*v2sigma2_4 + t17*t2 + t18*t2 + t4*vsigma_2 + t7*v2rhosigma_1 + t8*v2rhosigma_4;
}

/* machine-generated by xckernel; do not edit. */
// gga fxc coefficient channels, three gradient components.
static inline void xck_helfem_fxc_gga_3d(double grad_rho_p1_x, double grad_rho_p1_y, double grad_rho_p1_z, double grad_rho_x, double grad_rho_y, double grad_rho_z, double rho_p1, double v2rho2, double v2rhosigma, double v2sigma2, double vsigma, double & u, double & v_x, double & v_y, double & v_z) {
  const double t0 = 2*v2rhosigma;
  const double t1 = grad_rho_p1_x*grad_rho_x;
  const double t2 = grad_rho_p1_y*grad_rho_y;
  const double t3 = grad_rho_p1_z*grad_rho_z;
  const double t4 = rho_p1*v2rhosigma;
  const double t5 = 2*v2sigma2;
  const double t6 = grad_rho_x*t5;
  const double t7 = grad_rho_y*t5;
  const double t8 = grad_rho_z*t5;
  u = rho_p1*v2rho2 + t0*t1 + t0*t2 + t0*t3;
  v_x = 2*grad_rho_p1_x*grad_rho_x*grad_rho_x*t5 + 2*grad_rho_p1_x*vsigma + 2*grad_rho_x*t4 + 2*t2*t6 + 2*t3*t6;
  v_y = 2*grad_rho_p1_y*grad_rho_y*grad_rho_y*t5 + 2*grad_rho_p1_y*vsigma + 2*grad_rho_y*t4 + 2*t1*t7 + 2*t3*t7;
  v_z = 2*grad_rho_p1_z*grad_rho_z*grad_rho_z*t5 + 2*grad_rho_p1_z*vsigma + 2*grad_rho_z*t4 + 2*t1*t8 + 2*t2*t8;
}

/* machine-generated by xckernel; do not edit. */
// mgga_tau fxc coefficient channels, one radial gradient component.
// u multiplies the basis-function pair, v_r its radial derivative,
// w_tau (tau families) the pair's kinetic-energy density.
static inline void xck_helfem_fxc_mgga_tau(double grad_rho_p1_r, double grad_rho_r, double rho_p1, double tau_p1, double v2rho2, double v2rhosigma, double v2rhotau, double v2sigma2, double v2sigmatau, double v2tau2, double vsigma, double & u, double & v_r, double & w_tau) {
  const double t0 = grad_rho_r*v2rhosigma;
  const double t1 = 2*grad_rho_p1_r;
  const double t2 = grad_rho_r*v2sigmatau;
  u = rho_p1*v2rho2 + t0*t1 + tau_p1*v2rhotau;
  v_r = 2*grad_rho_p1_r*vsigma + 2*grad_rho_r*grad_rho_r*t1*v2sigma2 + 2*rho_p1*t0 + 2*t2*tau_p1;
  w_tau = rho_p1*v2rhotau + t1*t2 + tau_p1*v2tau2;
}

/* machine-generated by xckernel; do not edit. */
// Spin-resolved mgga_tau fxc channels, one radial gradient component.
// u_s multiplies the basis-function pair of spin s, v_s_r its radial derivative,
// w_s (tau families) the pair's kinetic-energy density.
// Polarized Libxc arrays keep their flat packing (v2rho2_0 = uu, _1 = ud, _2 = dd, ...).
static inline void xck_helfem_fxc_mgga_tau_spin(double grad_rho_a_p1_r, double grad_rho_a_r, double grad_rho_b_p1_r, double grad_rho_b_r, double rho_a_p1, double rho_b_p1, double tau_a_p1, double tau_b_p1, double v2rho2_0, double v2rho2_1, double v2rho2_2, double v2rhosigma_0, double v2rhosigma_1, double v2rhosigma_2, double v2rhosigma_3, double v2rhosigma_4, double v2rhosigma_5, double v2rhotau_0, double v2rhotau_1, double v2rhotau_2, double v2rhotau_3, double v2sigma2_0, double v2sigma2_1, double v2sigma2_2, double v2sigma2_3, double v2sigma2_4, double v2sigma2_5, double v2sigmatau_0, double v2sigmatau_1, double v2sigmatau_2, double v2sigmatau_3, double v2sigmatau_4, double v2sigmatau_5, double v2tau2_0, double v2tau2_1, double v2tau2_2, double vsigma_0, double vsigma_1, double vsigma_2, double & u_a, double & v_a_r, double & w_a, double & u_b, double & v_b_r, double & w_b) {
  const double t0 = grad_rho_b_r*v2rhosigma_1;
  const double t1 = grad_rho_a_r*grad_rho_b_p1_r;
  const double t2 = 2*grad_rho_a_p1_r;
  const double t3 = grad_rho_a_r*t2;
  const double t4 = 2*grad_rho_b_p1_r;
  const double t5 = grad_rho_b_r*t4;
  const double t6 = grad_rho_b_r*v2rhosigma_4;
  const double t7 = grad_rho_b_r*v2sigmatau_2;
  const double t8 = tau_b_p1*v2sigmatau_3;
  const double t9 = grad_rho_a_r*rho_a_p1;
  const double t10 = grad_rho_a_r*rho_b_p1;
  const double t11 = grad_rho_a_r*tau_a_p1;
  const double t12 = 2*tau_b_p1;
  const double t13 = grad_rho_b_r*t1;
  const double t14 = grad_rho_b_r*grad_rho_b_r;
  const double t15 = grad_rho_a_p1_r*v2sigma2_3;
  const double t16 = grad_rho_a_p1_r*grad_rho_b_r;
  const double t17 = 4*grad_rho_a_r*t16;
  const double t18 = 4*t13;
  const double t19 = grad_rho_a_r*grad_rho_a_r;
  const double t20 = t19*v2sigma2_1;
  const double t21 = t14*v2sigma2_4;
  const double t22 = 2*grad_rho_b_r;
  u_a = grad_rho_a_p1_r*t0 + rho_a_p1*v2rho2_0 + rho_b_p1*v2rho2_1 + t1*v2rhosigma_1 + t3*v2rhosigma_0 + t5*v2rhosigma_2 + tau_a_p1*v2rhotau_0 + tau_b_p1*v2rhotau_1;
  v_a_r = 4*grad_rho_a_p1_r*t19*v2sigma2_0 + grad_rho_a_r*t12*v2sigmatau_1 + grad_rho_b_p1_r*vsigma_1 + grad_rho_b_r*t8 + rho_a_p1*t0 + rho_b_p1*t6 + 2*t10*v2rhosigma_3 + 2*t11*v2sigmatau_0 + t13*v2sigma2_3 + t14*t15 + t17*v2sigma2_1 + t18*v2sigma2_2 + t2*vsigma_0 + t20*t4 + t21*t4 + t7*tau_a_p1 + 2*t9*v2rhosigma_0;
  w_a = grad_rho_a_p1_r*t7 + rho_a_p1*v2rhotau_0 + rho_b_p1*v2rhotau_2 + t1*v2sigmatau_2 + t3*v2sigmatau_0 + t5*v2sigmatau_4 + tau_a_p1*v2tau2_0 + tau_b_p1*v2tau2_1;
  u_b = grad_rho_a_p1_r*t6 + rho_a_p1*v2rho2_1 + rho_b_p1*v2rho2_2 + t1*v2rhosigma_4 + t3*v2rhosigma_3 + t5*v2rhosigma_5 + tau_a_p1*v2rhotau_2 + tau_b_p1*v2rhotau_3;
  v_b_r = grad_rho_a_p1_r*vsigma_1 + grad_rho_a_r*grad_rho_b_r*t15 + grad_rho_a_r*t8 + 4*grad_rho_b_p1_r*t14*v2sigma2_5 + grad_rho_b_p1_r*t19*v2sigma2_3 + grad_rho_b_r*t12*v2sigmatau_5 + rho_a_p1*t22*v2rhosigma_2 + rho_b_p1*t22*v2rhosigma_5 + t10*v2rhosigma_4 + t11*v2sigmatau_2 + t17*v2sigma2_2 + t18*v2sigma2_4 + t2*t20 + t2*t21 + t22*tau_a_p1*v2sigmatau_4 + t4*vsigma_2 + t9*v2rhosigma_1;
  w_b = rho_a_p1*v2rhotau_1 + rho_b_p1*v2rhotau_3 + t1*v2sigmatau_3 + t16*v2sigmatau_3 + t3*v2sigmatau_1 + t5*v2sigmatau_5 + tau_a_p1*v2tau2_1 + tau_b_p1*v2tau2_2;
}

/* machine-generated by xckernel; do not edit. */
// mgga_tau fxc coefficient channels, three gradient components.
static inline void xck_helfem_fxc_mgga_tau_3d(double grad_rho_p1_x, double grad_rho_p1_y, double grad_rho_p1_z, double grad_rho_x, double grad_rho_y, double grad_rho_z, double rho_p1, double tau_p1, double v2rho2, double v2rhosigma, double v2rhotau, double v2sigma2, double v2sigmatau, double v2tau2, double vsigma, double & u, double & v_x, double & v_y, double & v_z, double & w_tau) {
  const double t0 = 2*v2rhosigma;
  const double t1 = grad_rho_p1_x*grad_rho_x;
  const double t2 = grad_rho_p1_y*grad_rho_y;
  const double t3 = grad_rho_p1_z*grad_rho_z;
  const double t4 = rho_p1*v2rhosigma;
  const double t5 = tau_p1*v2sigmatau;
  const double t6 = 2*v2sigma2;
  const double t7 = grad_rho_x*t6;
  const double t8 = grad_rho_y*t6;
  const double t9 = grad_rho_z*t6;
  const double t10 = 2*v2sigmatau;
  u = rho_p1*v2rho2 + t0*t1 + t0*t2 + t0*t3 + tau_p1*v2rhotau;
  v_x = 2*grad_rho_p1_x*grad_rho_x*grad_rho_x*t6 + 2*grad_rho_p1_x*vsigma + 2*grad_rho_x*t4 + 2*grad_rho_x*t5 + 2*t2*t7 + 2*t3*t7;
  v_y = 2*grad_rho_p1_y*grad_rho_y*grad_rho_y*t6 + 2*grad_rho_p1_y*vsigma + 2*grad_rho_y*t4 + 2*grad_rho_y*t5 + 2*t1*t8 + 2*t3*t8;
  v_z = 2*grad_rho_p1_z*grad_rho_z*grad_rho_z*t6 + 2*grad_rho_p1_z*vsigma + 2*grad_rho_z*t4 + 2*grad_rho_z*t5 + 2*t1*t9 + 2*t2*t9;
  w_tau = rho_p1*v2rhotau + t1*t10 + t10*t2 + t10*t3 + tau_p1*v2tau2;
}
} // namespace xckernel
} // namespace helfem
